### ISSUE TITLE
[0.1.0] Severe Log Spam from Every Compat

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/ChosensModdedAdventure#10]
**Describe the bug**
Logspam is provided from Every Compat whenever resources reload. This leads to log files of massive size (I have one that is over 18mb, for example).

**To Reproduce**
1. Launch the game.
2. Trigger a resource-reload (switch resource packs, use the debug keycombo, change mipmaps, etc).
3. Observe the logs get cluttered.

**Modpack version**
0.1.0

**Additional context**
I did add Modernfix and Ferritecore to my instance, out of performance concerns. But I do not think these should affect it.

**Comment by ChosenArchitect** [comment]
Fixed in 0.1.1
