### ISSUE TITLE
Crashes When I Opening rituals from occultism

### ISSUE THREAD

**Issue by Xathridtech** [ChosenArchitect/ChosensModdedAdventure#102]
**Describe the bug**
Game crashes when I open the preview for Stregors Higher binding 
When I open Aviar Circle Issue happens as well

**To Reproduce**
1. obtain Dictionary of spirits
2. Open the ritual tab
3. Choose a ritual
4. click the eyball to preview the ritual
5. crash

**Expected behavior**
-> 1. obtain Dictionary of spirits
2. Open the ritual tab
3. Choose a ritual
4. click the eyball to preview the ritual
5. see a preview of the ritual with less opacity

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
-1 will post
**Modpack version**
->0.7.0
**Java Version**
->
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->43872 MB

**Additional context**
->

**Comment by Xathridtech** [comment]
[crash-2024-02-05_23.22.44-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14174669/crash-2024-02-05_23.22.44-client.txt)

**Comment by ChosenArchitect** [comment]
Seems this was fixed in the latest version of Occultism (fingers crossed) Pack updated 0.8.0 will have the fix
