### ISSUE TITLE
New Chunk not spawning chest properly

### ISSUE THREAD

**Issue by ashboy3093** [ChosenArchitect/ChosensModdedAdventure#103]
**Describe the bug**
-> When generating new chunks with world mender the chest with the world core does not always spawn and if it does it is in a weird place in the chunk (not the middle)

**To Reproduce**
1. Get a world Mender
2. Place a world core inside
3. Go to Y - 60 and search for chest 
4. 

**Expected behavior**
-> Before 0.4.1 and 0.5.0 the world core would be in the center of the chunk as expected.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.5.0
**Java Version**
->8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10GBs

**Additional context**
-> This is a world that worked fine on patch 0.4.0. I made a new world and the spawn chunk had the same problem so I am assuming it is all spawned chunks.

**Comment by immortius** [comment]
Randomized location of the chest was added in a recent Chunk By Chunk mod version, so this is working as intended on my end (as the Chunk By Chunk mod author). The height range is configurable so the modpack could lock it to Y = -60 if desired.
