### ISSUE TITLE
Modpack Randomly Decides to Not Work

### ISSUE THREAD

**Issue by Atlas-19** [ChosenArchitect/ChosensModdedAdventure#104]
**Describe the bug**
-> Occasionally it works, and seems to work fine if you do not tamper with anything at all, usually after a fresh install. But if you do tamper with it like installing another mod, after game launches and Forge loads the mods the game menu briefly appears before game's regular loading screen appears. After the progress bar reaches near the end and stays there for some time the game closes. occasionally the sound get glitched and gets stuck for about 20 second before closing.
Tampering just looks like a surefire way to get it to break but it also happens randomly. It might work before you close the game and the next time you launch it it just doesn't work.

**To Reproduce**
1. Install the modpack
2. Launch the modpack

**Expected behavior**
-> Expected the game to start and work when launched

**Modpack version**
-> 0.7.0

**Java Version**
-> Openjdk and Temurin 21, 17

**Modpack Launcher Used**
-> Forge 47.2.19

**Ram Allocated**
-> 8192MB

**Additional context**
-> I use Linux, specifically EndeavourOS, but I have tried to run the modpack under Wine and the issue persisted. As for the game launcher I use ATLauncher, if that'll make a difference.

Here's a sample of the game logs. They all look more or less the same each time:
[latest.log](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14199771/latest.log)

And here is what I think is a crash report. These appear directly under the instance folder whenever the game closes after the mods are loaded, not in the crash_reports folder:
[hs_err_pid93531.log](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14199786/hs_err_pid93531.log)

**Comment by immortius** [comment]
For what it is worth:
1) In the crash log minecraft is only allocated 4G ram, not 8
2) The crash is happening in the audio subsystem (openAL) so you might try audio driver or openal updates.

**Comment by ChosenArchitect** [comment]
I hope giving it more ram fixed your issue! I don't have a way of testing modpacks on Linux and don't know anything about it, unfortunately.

**Comment by Atlas-19** [comment]
I had already tried changing the RAM many times when I posted this issue. But I was well into "see what sticks" mode at the time of this crash log so I had also stopped adjusting the RAM every time.

As I said, the issue persisted under Wine which creates a Windows environment for programs so perhaps you need not to test it on Linux? But idk.
Thanks for the attention.

**Comment by Atlas-19** [comment]
Ok, I think installing openal-git package from [Chaotic-AUR](https://aur.chaotic.cx/) solved it.
I did try installing OpenAL but I installed the openal package from the extra repo and that didn't do anything. But the openal-git package from Chaotic-AUR specifically solves the problem.
This is what it looks like so far at least. But I don't think it will suddenly stop working in future.

**Comment by Atlas-19** [comment]
Well, that didn't last long... Yea, it went back to crashing after I installed two other mods.
