### ISSUE TITLE
Server 0.7.1 and Client Incompatible FML modded server. Server mod list is not compatible.

### ISSUE THREAD

**Issue by nwbair** [ChosenArchitect/ChosensModdedAdventure#107]
**Describe the bug**
After the latest update to 0.7.1, client machines show a Red X with "Incompatible FML modded server. Server mod list is not compatible."

**To Reproduce**
1. Launch Minecraft from CurseForge
2. Select Multiplayer
3. Find server in the list and notice the red X on the right.4. 

**Expected behavior**
-> This red X should not appear.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.7.1
**Java Version**
-> Server is running OpenJDK 17.0.9. Client is running whatever CurseForge uses when running Minecraft.

**Additional context**
-> I thought maybe there was an issue with the update. I set up a brand new temporary server from the latest server pack and did a clean Update to a New Profile. I still get the same red X. This leads me to believe that the client and server packs are out of sync.

**Comment by ChosenArchitect** [comment]
Im am updating to 0.8.0 and I will be doing server compat to make sure everything works as it should!
