### ISSUE TITLE
Easy Magic not working

### ISSUE THREAD

**Issue by agreedSkiing** [ChosenArchitect/ChosensModdedAdventure#108]
**Describe the bug**
From the mods own curse forge page
> ▶️ Not compatible with [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) and the matrix enchanter from [Quark](https://www.curseforge.com/minecraft/mc-mods/quark).

Block also states that the item is from functional blocks.
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/93997033/5a4b7710-6030-43d5-86d1-d0547e6192d2)

**To Reproduce**
1. Start a new world in creative
2. Place enchanting table
3. Open table
4. No reroll button

**Expected behavior**
The interface from easy magic

**Screenshots**

**Modpack version**
->  0.7.1
**Java Version**
-> 21.0.2 oracle
**Modpack Launcher Used**
-> Prism launcher
**Ram Allocated**
-> 12288 MiB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I will be removing the mod from the latest version as it seems to have never worked... oversite on my part
