### ISSUE TITLE
Statues crashes the server and client worlds

### ISSUE THREAD

**Issue by agreedSkiing** [ChosenArchitect/ChosensModdedAdventure#109]
**Describe the bug**
When creating a killer II or higher statue from statues the mod with other mods crashes the game.

**To Reproduce**
1. Create a new world
2. Find a statue
3. Create a statue core
4.  Insert statue core in statue
5. Kill 20 mobs
6. Improve the statue with killer 1
7. Place statue, works fine
8. Improve the statue to killer 2
9. When the statue tries to kill the mob the game crashes

**Expected behavior**
No crash of the client or world, see the fix in https://github.com/ShyNieke/StatuesMod/issues/95

**Screenshots**

**Modpack version**
-> 0.7.1

**Java Version**
-> 21.0.2 oracle
**Modpack Launcher Used**
-> Prism launcher
**Ram Allocated**
 -> 12288 MiB

**Additional context**
This has been fixed in statues 4.0.3

**Comment by ChosenArchitect** [comment]
Looking into this and will be updating the mod I hope that fixes the issue! Thanks for the fantastic report!
