### ISSUE TITLE
[0.1.0] Fireproof Boats version to high

### ISSUE THREAD

**Issue by lays24mc** [ChosenArchitect/ChosensModdedAdventure#11]
**Describe the bug**

In the latest version of the modpack, the mod version of "Fireproof Boats" is set too high. This causes the server to stop on startup.

Crashlog: https://pastebin.com/StUfv1Qw 

The message with MegaCells can be ignored, because I removed AE2+Addons to check and get a good Crashlog. Otherwise, there is only an exit code from the launcher.

**Comment by ChosenArchitect** [comment]
wait that mod shouldn't even be in the pack?

**Comment by ChosenArchitect** [comment]
Seems I sent a disabled version of the mod jar to the server... will be fix in next update

**Comment by lays24mc** [comment]
I did another clean install on the client just to be sure:

![grafik](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/38819519/f4fd4ec1-b914-4ee8-a06b-298161c8537e)

**Comment by ChosenArchitect** [comment]
fixed in 0.1.1 server files
