### ISSUE TITLE
modpack (v.0.8.0) fails to update or install because of Windows Defender detects trojan

### ISSUE THREAD

**Issue by Elendol** [ChosenArchitect/ChosensModdedAdventure#113]
**Describe the bug**
Installation interrupted by windows defender because it detects "Trojan:Script/Wacatac.B!ml" when unzipping mods for installation.

I am not sure if this is a false positive or if there is a compromised mod.

**To Reproduce**
1. Start curseforge application on MS Windows 11 
2. Update modpack OR update modpack on new profile OR install modpack from scratch

**Expected behavior**
Modpack updates or installs without threat detection

**Screenshots**

You can see here my multiple blocked attemps

![Screenshot 2024-03-10 123328](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/66071502/5038f764-e586-4f20-9554-81c1e8a7c58e)

**Modpack version**
v.0.8.0

**Java Version**
N/A

**Modpack Launcher Used**

Curseforge v.0.246.2-16724

**Ram Allocated**
N/A

**Additional context**
To try to eliminate some issue from the curseforge client I tried to install another modpack (ATM 9 no frills), no issue with it.

**Comment by Elendol** [comment]
same issue from unzipping the server files
Edit: Defender being more helpful there, this is an issue with the Nether's Overhaul mode:  `CMA Server Files 0.8.0\CMA Server Files 0.8.0\mods\Nether's Overhaul-1.20.1_V1.3.6.jar`

**Comment by ChosenArchitect** [comment]
This is 100% a false positive as Curseforge scans everything when it enters and leaves their website. I also run Windows Defender, put everything together on my system, and had no issues. Now when you say install mods? I have no idea what you are talking about there as you don't need to unzip anything outside of the server pack if you want to make a server. This being said JARs are considered suspicious sometimes as they are a java executables.
