### ISSUE TITLE
Crashes When I get hit by skeletons sometimes

### ISSUE THREAD

**Issue by SonicNico** [ChosenArchitect/ChosensModdedAdventure#114]
**Describe the bug**
-> Sometimes when I get hit, it completely crashes the server. I think it's specifically skeletons with melee weapons, but I can't say for certain, as i get hit and the server crashes, sometimes I get hit and it doesn't crash.

**To Reproduce**
1. Get hit by mob
2. Server Crashes
3. 
4. 

**Expected behavior**
-> Get hit by skeleton, continue playing the game

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.8.0
**Java Version**
->
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 8GB

**Additional context**
-> I think it is skeletons in particular, but I could be wrong. I noticed it happening more frequently in the nether, though.
[crash-2024-03-14_20.55.30-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14609378/crash-2024-03-14_20.55.30-server.txt)

**Comment by ChosenArchitect** [comment]
Im looking into this and will work on a update this weekend!

**Comment by SonicNico** [comment]
> Im looking into this and will work on a update this weekend!

Awesome! Thanks! Turns out it's also happened to one of my friends as well.

**Comment by ChosenArchitect** [comment]
Moving everything to one thread #124
