### ISSUE TITLE
Ender IO Item Filter missing from v0.8.0

### ISSUE THREAD

**Issue by Gabripouele** [ChosenArchitect/ChosensModdedAdventure#115]
**Describe the bug**
Ender IO Basic Item Filter and Advanced Item Filter are missing from the modpack. (Couldnt find them through JEI at all searching with tags and keywords)

**To Reproduce**
1. Launch the modpack.
2. Open the inventory.
3. Search for Basic Item Filter in JEI.
4. Notice the Basic Item Filter is missing.
5. Repeat steps 3 and 4 for Advanced Item Filter.

**Expected behavior**
Item Filter and Advanced Item Filter are available in JEI and to be used/crafted in the modpack.

**Screenshot**
![2024-03-17_19 38 33](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/139871774/a7c9fa6d-c8d1-4e9a-9ef0-851a947005ef)

**Modpack version**
-> 0.8.0
**Java Version**
-> n/a
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 8 GB

**Additional context**
Existence of this feature was obtained from the wiki:
https://ftbwiki.org/Basic_Item_Filter
https://ftbwiki.org/Advanced_Item_Filter

**Comment by Leskinak** [comment]
unfortunately, the Ender IO verison for 1.20 and more is still in progress and the item filter seems to not be implemented yet !
after the session in discord with @ChosenArchitect tonight, i had the information from him directly. 
:(
sorry i should have dig further before pushing you to enter a ticket for it !
can close as not a bug!

**Comment by ChosenArchitect** [comment]
All good 😊 sorry I'm late to get into the bug reports. I'm only able to check every other week when I work on updates.
