### ISSUE TITLE
Ancient Compass UtilitiX

### ISSUE THREAD

**Issue by sannaito** [ChosenArchitect/ChosensModdedAdventure#116]
**Describe the bug**
Massive tick lag with Ancient Compass

**Modpack version**
0.8.0
->
**Java Version**
->JDK 17
**Modpack Launcher Used**
->Prism Launcher
**Ram Allocated**
->8gb on client and 12gb on server

**Comment by ChosenArchitect** [comment]
Mod updated in latest update that should fix this
