### ISSUE TITLE
[FTBUltimine] Snow on top of block is unbreakable with an empty hands or other random items other than a Shovel or equivalent when using the FTBultimine mod.

### ISSUE THREAD

**Issue by Leskinak** [ChosenArchitect/ChosensModdedAdventure#117]
**Actual Result**
Upon using the _FTBultimine_ mod on snow carpet on top of blocks, the animation of breaking and the area covered is displayed, but the asset disappear shortly and reappear having the feature only usable with either a shovel or another tool that will be usable on snow.

Before updating to 0.8.0, the snow was breaking but not dropping the snow balls as intended, now the snow remains and force the user to gather snowball even if he don't want to.

**Steps To Reproduce**
1. Launch the modpack on version 0.8.0
2. Proceed in a snow biome.
3. Use the FTBUltimine mod on shapeless mode with snow carpet with an empty hand 
4. Notice that the snow carpet asset remains after the animation is done.

**Expected behavior**
The snow carpet disappear and the snowball are voided when broken without the proper tool.

**Modpack version**
0.8.0
**Java Version**
Latest CurseForge Launcher
**Modpack Launcher Used**
CurseForge
**Ram Allocated**
20gb

**Additional context**
this issue has been reproduced in 5 out of 5 attempts.
this issue has been reproduced with the following mod of FTBultimine:   
-Shapeless
-Small Tunnel
-Large Tunnel

**Comment by Leskinak** [comment]
![#117](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/164125534/aebf8ec4-37d7-455a-a88c-cbb6a7e75121)

**Comment by Leskinak** [comment]
https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/164125534/58eaae95-ad15-4d64-ac2f-561110f9936e

**Comment by ChosenArchitect** [comment]
Seemes to be working when I did some more testing however It might be something to do with claimed chunks that could be causing this not work work

**Comment by gaminggirl** [comment]
Happens for me to in 0.9.1, both inside and outside of claims.
