### ISSUE TITLE
Lava bucket compacting recipe been overridden by twigs 

### ISSUE THREAD

**Issue by unkidrik** [ChosenArchitect/ChosensModdedAdventure#118]
**Describe the bug**
->When i try to make a lava bucket by compacting the recipe is been over ridden by the twigs gravel bricks recipe. this happens no matter what order items are put into basin

**To Reproduce**
1. take 8 gravel 8 flint and a bucket
2. place into basin below mechanical press in any order
3. makes 4 gravel bricks and stops
4. 

**Expected behavior**
->expected to make a bucket of lava

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->cma chunk by chunk 0.8.0
**Java Version**
->
**Modpack Launcher Used**
->Atlauncher
**Ram Allocated**
->10gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
So in cases like this you need to use the filter on the basin. Now typically the best way to do this would be to use a create item filter and drag the lava bucket from JEI into the filter. However I will look into this and see if I can't potentially fix this in some way next update.
