### ISSUE TITLE
[Integrated Dynamics] User get disconected after interacting with the Item Pannel of Integrated Dynamics in a specific farm setup.

### ISSUE THREAD

**Issue by Leskinak** [ChosenArchitect/ChosensModdedAdventure#119]
**Describe the bug**
After interacting with the Item Panel of the Integrated Dynamics mod, user is getting disconnected with an error message.
This issue does not occur with any other setup of Functional Storage and Integrated Dynamics in our world.
This issue started to occurred after updating to 0.8.0.
Mod used in the farm:
-Create
-Botany Pots
-Integrated Dynamics.
-Functional Storage.

**To Reproduce**
1. Launch application on version 0.8.0
2. Proceed to create a farm with Functional Storage, Create, and Integrated Dynamics. (or load the save file and proceed to the coordinate)
3. Interact with the Integrated Dynamics item panel
4. Notice that the user is disconnected and have an error message displayed

**Expected behavior**
Application remains stable at all time

**Screenshots**
![IntegratedDynamics_Crash](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/164125534/380fda89-06e1-40e3-a2a6-f567e3f38708)

**Modpack version**
0.8.0
**Java Version**
Curse Forge current version
**Modpack Launcher Used**
Curse Forge
**Ram Allocated**
20gb server 
15gb client

**Additional context**
-> I can provide the Save World Data if needed since it seems to be related to a specific setup.
-> This issue does not occur with any other Item Terminal of Integrated Dynamics in our world and we have over 8 other setup of Storage Controller and Integrated Dynamics storage item mixed together.
-> Location of the farm:
 -X=918
 -Y=75
 -Z= 4275

**Comment by Leskinak** [comment]
https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/164125534/d5ee1775-6ef0-48da-8e5f-d8b3eadaa160

**Comment by Leskinak** [comment]
here is a small tour of the factory if it can help

**Comment by ChosenArchitect** [comment]
This still needs further testing as its hard for me to reproduce and know exactly what the issues is.

**Comment by 5ully** [comment]
We would need full information on the setup, because reproducing this seems quite hard without the exact setup. The most common type of packet error is when the pack is too large.
