### ISSUE TITLE
minecraft wont respond.

### ISSUE THREAD

**Issue by Ihavetherights** [ChosenArchitect/ChosensModdedAdventure#12]
**Describe the bug**
-> I load my start loading my world, it runs through loading all mods, and then it gets stuck, never gets to world building.
I tried making a fresh world, same thing.
I tried running a backup, same thing.
I figured out it was Ars Neuvo Acceleration so i disabled Ars and it works. but i love Ars just as much as you, i would like to play with it.. Check additional content for a snip it of the crash report

**To Reproduce**
1. load up world?
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.1..1
**Java Version**
-> 8
**Modpack Launcher Used**
-> Curse Forge 
**Ram Allocated**
-> 8GB

**Additional context**
->
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ars_nouveau/glyph_accelerate.toml of type SERVER for modid ars_nouveau

**Comment by MalaChaiLatte** [comment]
Update to the latest version and use java 17, If this doesn't fix it then post a log

**Comment by ChosenArchitect** [comment]
should be fixed in newer versions of the pack
