### ISSUE TITLE
Strange bug where every entity gets pulled down

### ISSUE THREAD

**Issue by zoey-amon** [ChosenArchitect/ChosensModdedAdventure#120]
**Describe the bug**
-> Randomly when playing on a LAN world, every entity including players will suddenly start being pulled downwards every few seconds, even in creative mode.

Not sure how to reproduce, since it happens seemingly at random.

**Screenshots**
https://youtu.be/zLl9AbGujcc?si=IWlw5QA8vo5RrFDQ 
video link of proof

**Modpack version**
-> 0.8.0
**Java Version**
->1.8.0_321
**Modpack Launcher Used**
->ATLauncher
**Ram Allocated**
-> 7,168mb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
So this is actually not a bug but is a lunar event that has occurred and shows up in your chat.

**Comment by zoey-amon** [comment]
ah! i feel silly for not realizing that. thank you!
