### ISSUE TITLE
Suggestion : Create More Drill Heads

### ISSUE THREAD

**Issue by jinkhya** [ChosenArchitect/ChosensModdedAdventure#121]
**Is your feature request related to a problem? Please describe.**
-> Create Drills cannot be enchanted/tweaked by default

**Describe the solution you'd like**
-> It'd be nice to be able to put at least silk touch or fortune.

**Mod Sugestions**
-> Create More Drill Heads : https://www.curseforge.com/minecraft/mc-mods/create-more-drill-heads

Thanks in advance :)
Jin

**Comment by ChosenArchitect** [comment]
Added in the next update!
