### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by CrayonMelter** [ChosenArchitect/ChosensModdedAdventure#122]
Last night I seen that a few of the mods in the pack had an update, so this morning is curse forge i updated all the mods. after that i tried to start the game and i get a crash. im not good with all the code stuff and just need some help fixing this so i can keep playing 

this is the crash report i get 
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Thermal Series (thermal) encountered an error during the done event phase

**Comment by ChosenArchitect** [comment]
well if you updated the mods yourself then I cant help you! When I push a pack update I make sure all the mods updated work together as some won't if you just update everything. It is not recommended to update mods unless you know what you are doing and know how to fix issues that pop up.
