### ISSUE TITLE
0.9.0 server crashing / reliquary ticking entity

### ISSUE THREAD

**Issue by 0xc0ffea** [ChosenArchitect/ChosensModdedAdventure#123]
updated our family 0.8.0 home server to 0.9.0 and almost immediately had server crashes relating to mobs & reliquary drops.

Our limited testing suggested it it was related to mob drops

Crash reports attached.

[crash-2024-04-07_17.45.00-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14899171/crash-2024-04-07_17.45.00-server.txt)
[crash-2024-04-07_17.36.20-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14899173/crash-2024-04-07_17.36.20-server.txt)
[crash-2024-04-07_17.00.59-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14899174/crash-2024-04-07_17.00.59-server.txt)
[crash-2024-04-07_16.53.09-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14899175/crash-2024-04-07_16.53.09-server.txt)
[crash-2024-04-07_16.16.46-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14899176/crash-2024-04-07_16.16.46-server.txt)

There is a similar issue on the reliquary Github https://github.com/TrainerGuy22/Reliquary/issues/244

**Comment by hikinata** [comment]
same thing
[crash-2024-04-09_19.15.51-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/14921980/crash-2024-04-09_19.15.51-server.txt)

**Comment by ozamweymat** [comment]
me too bro
had to delete the mod

**Comment by 0xc0ffea** [comment]
> me too bro had to delete the mod

We rolled back to 0.8.0 and are going to stick with that till this gets fixed, if it doesn't .. then 0.8.0 is where the game ends.

**Comment by 5ully** [comment]
The issue you linked to the reliquary github is the old reliquary and that mod is not in Chosen's modpack. Taken from your crashlog:
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/9050688/a8f26767-f03d-4663-bfd5-547dc5cf03a6)

**Comment by hikinata** [comment]
Do not go back to 8.0.0, but just change the reliquary mod to the latest version in 1.20.1. it works perfectly

**Comment by ChosenArchitect** [comment]
Im looking into this and will work on a update this weekend!

**Comment by ChosenArchitect** [comment]
Will be fixed in the latest update!
