### ISSUE TITLE
Nether Wart Duplication

### ISSUE THREAD

**Issue by Bjeeba** [ChosenArchitect/ChosensModdedAdventure#125]
More of an oversight than a bug (since I'm sure it can be fixed by adjusting some crafting recipes)

-Four nether wart in a 2x2 will craft a nether wart block
-nether wart blocks can be crafted into 9 nether wart
-repeat for infinite nether wart duplication

**Comment by ChosenArchitect** [comment]
Thanks for the info! This is 100% due to something adding the 2x2 craft as it's normally a 3x3 craft. I'll change some recipes in the next update!

**Comment by ChosenArchitect** [comment]
Fixed in the next update!
