### ISSUE TITLE
Golems from GeOre behaving very differently from the Ars amethyst golem

### ISSUE THREAD

**Issue by malachimdube** [ChosenArchitect/ChosensModdedAdventure#127]
**Describe the bug**
GeOre golems presumably should behave identically to the amethyst golem from Ars. Instead, they seem to stand in place permanently are always either speeding up cluster growth or harvesting shards, and don't break clusters when harvesting shards, resulting in a rate of production at least 3 times that of the amethyst golems.

**To Reproduce**
Created two equally sized fenced off areas with 15 blocks of amethyst in one and 15 blocks of diamond geore in the other. In the respective area, spawn two geore/amethyst golems and use the wand of dominion to set their home to a drawer in each enclosure, then wait.

**Expected behavior**
The geore golems should behave roughly the same as the amethyst golems.

**Modpack version**
->0.9.1
**Java Version**
->17.0.8
**Modpack Launcher Used**
->ATLauncher
**Ram Allocated**
->8GB

**Comment by 5ully** [comment]
Nice, I know MrBysco has a github page for their mod too, can you report it here too? Probably quicker than me asking for every question xd
https://github.com/Mrbysco/GeOre/issues/new/choose

**Comment by ChosenArchitect** [comment]
So they seem to be working as intended and the code just the same as the base mod for the function of the golems. Now the animations will sometimes break with the shaders in the pack so for the movement this might be causing the lack of movement.
