### ISSUE TITLE
Occultism Spirit Crushers Partially Broken!

### ISSUE THREAD

**Issue by Grimlock7** [ChosenArchitect/ChosensModdedAdventure#128]
**Describe the bug**
-> The Spirit crushers fail to produce Dust when you try to crush ores belonging to Occultism. Instead it drops Barrier Blocks. This issue occured with Iesnium Ore.

**To Reproduce**
1. Give Iesnium Ore + Potentially others to the Crusher
2. The Crusher Gives you back Barrier Blocks instead of the specific Dust
3. 
4. 

**Expected behavior**
-> The Crusher should turn the ore into the correct Dust. Basic Crusher from 1 Dust to 2, and higher tiers from 1 to 4 or 6

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.9.1
**Java Version**
->1.20.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
-> 10GB

**Additional context**
->This other related github issue seems to potentially point the issue towards being a KubeJS unification issue. Here is the link, this may be a potential fix. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3504#issuecomment-1710914223

**Comment by ChosenArchitect** [comment]
Im going to see if I can fix that today! This might be a mistake on my end with the kubejs datapacks

**Comment by ChosenArchitect** [comment]
So I did some testing to see if I could reproduce and I cant seem to get the same result. I did update the forge version before testing, however! This might be a fix (not sure) but everything seems to be working fine on testing.
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/fcc12580-b124-411c-9d57-2bd479a59b7e)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/daf84f34-ef05-4260-9ca3-6a722fac0220)

**Comment by Grimlock7** [comment]
So I did a bit more testing and found out, in single player, the crushers work as expected and drop dust, but on servers, the issue occurs, so it might be something regarding how the ores are unified or on a script that runs specifically on servers.

**Comment by Grimlock7** [comment]
Hey, Did you successfully fix the issue on servers then? If so great to hear!

**Comment by ChosenArchitect** [comment]
I did push a update today. I didn't test the crushers on server side but I can do so this afternoon. The unifying mod did revive a update but I am handling a lot of the crusher recipes with kubejs data packs.

**Comment by Grimlock7** [comment]
Hey, Hope Testing the issues on a server is going well. I just noticed that the issue is also occurring in the Ore Miner Lamp/Dimensional Mineshaft. Just thought I should let you know.

![orZ04S5MJW](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/30302995/5a761156-76db-432b-8845-837f966fc504)
