### ISSUE TITLE
Glove Slot Missing from Inventory

### ISSUE THREAD

**Issue by calliereimann** [ChosenArchitect/ChosensModdedAdventure#129]
**Describe the bug**
-> When looking at the equipment slots in the player inventory, no Gloves slot exists. The Glove items from the Aether mod can be equipped, but only by right clicking while holding them. When this is done, they vanish completely and cannot be removed unless swapped with another Aether glove or destroyed via durability. 

**To Reproduce**
1. Craft Leather Gloves with two leather in a crafting table.
2. Right Click while holding the gloves. 
3. Observe that the gloves are visible on the player model
4. Look through the equipment slots and realize that the glove item is not there. 

**Expected behavior**
-> In between the Hands equipment slots and the Ring equipment slots, there should be a Gloves equipment slot which allows for Glove items to be equipped and removed. Notably, the slot _does exist_, because Glove items can be equipped, it's just not _visible to the player_, for an unknown reason. 

**Suggested Fix**
-> Either change the Aether mod's Glove items to use the Hands slot, or make the Glove slot visible to players. 

**Modpack version**
-> 0.9.1 
**Java Version**
-> 17
**Modpack Launcher Used**
-> Prism Launcher 8.3
**Ram Allocated**
-> 7680 MB 

**Additional context**
->

**Comment by ChosenArchitect** [comment]
So there's actually a slot specifically for equipment for the Aether that is a button in the top right corner of the little view window that shows your character when you're in your inventory. A lot of the ather equipment goes in a very specific place in that GUI.

**Comment by calliereimann** [comment]
You're right, sorry. I completely glanced over the cloud icon and assumed that it wasn't an equipment section. Thank you, and sorry for reporting a non-bug!
