### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by drkanbs** [ChosenArchitect/ChosensModdedAdventure#14]
Create: Stuff and Additions.   I checked a week ago and it hadn't yet update to 1.20.1, but I just looked today, Oct 2nd if read later, that it has been.  It's a fun, well addition to create. 
https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions

**Comment by ChosenArchitect** [comment]
Its in the modpack already
