### ISSUE TITLE
Crashes When attempting to load modpack

### ISSUE THREAD

**Issue by drkanbs** [ChosenArchitect/ChosensModdedAdventure#15]
**Describe the bug**
-> I have no idea what happened.  Something about borderless fullscreen and rubidium? 

**To Reproduce**
1.  All I did was attempt to load the modpack on the FTB launcher

[crash-2023-10-02_13.14.12-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12785282/crash-2023-10-02_13.14.12-client.txt)

**Comment by MalaChaiLatte** [comment]
Try turning off rubidium. This issue is normally cause by optifine, which would suggest it could be to do with similar mods such as rubidium. 
Also, I would suggest a different launcher than FTB

**Comment by MalaChaiLatte** [comment]
Try updating to the latest version, this should have been fixed

**Comment by ChosenArchitect** [comment]
if you experience this again in the new version be sure to let me know!
