### ISSUE TITLE
CurseForge Page: Add "Small/Lightweight" to Categories

### ISSUE THREAD

**Issue by thisisnotchicken** [ChosenArchitect/ChosensModdedAdventure#16]
Hi Chosen,

I saw that this is a relatively lightweight modpack at the moment. Could you add the "Small/Lightweight" category to the CurseForge page? If there are plans to expand this to medium size in the future, that's alright too, I'd just appreciate that clarification.

Thanks,
Max

**Comment by ChosenArchitect** [comment]
I wouldn't call this a light modpack as it have over 250 mods

**Comment by thisisnotchicken** [comment]
Sorry for my misunderstanding, as I'm still somewhat new to modded MC. However, I want to mention that I found at least one modpack [here](https://www.curseforge.com/minecraft/modpacks/bigchadguys-plus) with about the same amount of mods as this one under the "Small/Lightweight" category.

**Comment by MalaChaiLatte** [comment]
The majority of the mods in that pack are small addon mods and qol/performance mods

Edit: That pack is also fabric, which tends to have smaller mods in general.
