### ISSUE TITLE
Tick Accele-Rat-or not AcceleRating

### ISSUE THREAD

**Issue by chadle01** [ChosenArchitect/ChosensModdedAdventure#19]
**Describe the bug**
I'm not suuuuper good at this mod so maybe im just wrong, but the wiki says you make the upgrade, give it to the rat place rat above or below block and it accelrates approximately 5x speed, but nots accelerating at all for me.
->

**To Reproduce**
1. Tame Rat
2. Craft Rat Accele-Rat-or
3. Placee Rat Accel-Rat-or in rat inventory
4. Place rat above or below a block such as a furnace, Imbument Chamber

**Expected behavior**
->Expected affected block to move through its process 5x faster

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.1
**Java Version**
->1.20.1
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8g

**Additional context**
->
![2023-10-03_07 36 23](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/47267047/586ffa32-8fce-4f47-afcf-5b5ba32c5784)
![2023-10-03_07 37 21](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/47267047/7905250d-c1b5-4dff-bf08-53f315bb372b)

**Comment by ChosenArchitect** [comment]
So, did some testing and it does work but it only accelerates a little bit you need more than one rat to make it go really fast
