### ISSUE TITLE
Sorting lags like crashing

### ISSUE THREAD

**Issue by kragnoth** [ChosenArchitect/ChosensModdedAdventure#20]
**Describe the bug**
->

When middle click sorting (after clearing the only keys that say sort using the new version of controlling... ) I get the following:

Immense time out lag for about 10 seconds

"java.lang.illegalstateexception: unequal before and after item counts" in text on screen

**To Reproduce**
1. load modpack
2. middle click inventory
3. lag
4. gibberish text that gives no helpful answers

**Expected behavior**
-> the ability to sort when using a mod that sorts... which I'm not sure which mod actually adds sorting keys in this modpack, as I'm not familiar with all of them, but none of them really look like they add sorting based on names

**Modpack version**
-> .11
**Modpack Launcher Used**
-> gdlauncher
**Ram Allocated**
-> 8 gigs

What mod adds the sorting?

**Comment by ChosenArchitect** [comment]
Unfortunately the lag does occur on the first sort each time you learn into the world. As of right now there's no good sorting mod so I'm stuck with this janky way of doing it. Hopefully win something like quark updates I will be able to fix this issue!

**Comment by ChosenArchitect** [comment]
FIXED FINALY in the latest Update!!! :D
