### ISSUE TITLE
Breaking magnolia boats will give you a different boat

### ISSUE THREAD

**Issue by NubPlyzz** [ChosenArchitect/ChosensModdedAdventure#21]
**Describe the bug**
-> when crafting a magnolia boat (havent tested if u spawn one with a dispencer etc.) and breaking it will give you a random boat from any other wood in the modpack that has a boat available

**Expected behavior**
-> get ur magnolia boat back

**Modpack version**
-> 0.0.3 (Beta) [havent tested later versions]
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Curseforge

**Comment by ChosenArchitect** [comment]
You are not on the latest version of the mod pack. The latest version of the mod pack is 0.1.3. please be sure to update.
