### ISSUE TITLE
Crashes When I Open My Colossal Chest

### ISSUE THREAD

**Issue by NubPlyzz** [ChosenArchitect/ChosensModdedAdventure#22]
**Describe the bug**
-> when standing on the geysers which spawn in snowy biomes you get an infinite levitation effect that doesnt go away even after moving away from the specific coordinates. even after /home it doesnt go away untill you die (or possibly drink milk)

**Expected behavior**
-> levitation only when standing on the block (idk for how long the levitation goes on  when standing on them and till how high it goes)

**Modpack version**
-> 0.0.3 
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
->Curseforge

**Additional context**
-> when taking damage (from a zombie as far as i know but idk if different mobs would effect the downwards knockback recieved)  it will jerk you down quite a bit (about 1,5 blocks)

**Comment by ChosenArchitect** [comment]
You are not on the latest version of the mod pack. The latest version of the mod pack is 0.1.3. please be sure to update.
