### ISSUE TITLE
Mod Suggestion: Mekanism And Applied Mekanistics

### ISSUE THREAD

**Issue by fred21O4** [ChosenArchitect/ChosensModdedAdventure#23]
**Mod Sugestions**
-> [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism) 
-> [Mekanism Generators](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators) 
-> [Mekanism Tools](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools) 
-> [Applied Mekanistics](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)

**Comment by MalaChaiLatte** [comment]
This will probably not occur, chosen has stated he wants this to be more of a simple pack and that mekanism would over complicate it

**Comment by fred21O4** [comment]
Ah that's a shame but understandable.
