### ISSUE TITLE
the "guide book" does not work

### ISSUE THREAD

**Issue by Macin57** [ChosenArchitect/ChosensModdedAdventure#24]
**Describe the bug**
->when you try to interact with the book it doesn't do anything.

**To Reproduce**
1. Spawn into a new world
2. rightclick with the "guide book"
3. 
4. 

**Expected behavior**
->i expected it to open some sort of GUI or such.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->0.1.3
**Java Version**
->
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->8GB

**Additional context**
![2023-10-04_10 40 14](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/146930847/b8357101-de04-4920-9fb9-676c7725f499)

->

**Comment by ChosenArchitect** [comment]
fixed in next update 0.1.4
