### ISSUE TITLE
The task "Kill the llamas" gets completed when killing a zombie

### ISSUE THREAD

**Issue by Macin57** [ChosenArchitect/ChosensModdedAdventure#25]
**Describe the bug**
->I've died and when i collected my items a zombie dropped onto myself, so I killed him and the task "kill the llamas" got marked as finished, (I have not killed any llamas according to my statistics.)
tried to reproduce, and it happened again on a new world
**To Reproduce**
1. die
2. collect your items
3. Kill a zombie
4. 

**Expected behavior**
-> for it to not happen
**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2023-10-04_11 45 55](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/146930847/0f408a20-5631-4add-a452-40d165885f88)
![2023-10-04_11 45 22](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/146930847/4b9f6128-6a95-498c-9792-e9976766e431)

**Modpack version**
->0.1.3
**Java Version**
->
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
fixed in  0.1.4
