### ISSUE TITLE
User disconnected from Server when attempting to craft Jukebox from JEI in Integrated Storage's Crafting Terminal

### ISSUE THREAD

**Issue by dreadstuff** [ChosenArchitect/ChosensModdedAdventure#26]
**Describe the bug**
-> Internal Exception error when attempting to craft a jukebox within the crafting grid for Integrated Storages Item Crafting - completely disconnects user (myself) and jukebox is not created (manual receipe works fine, but trying to select the recipe build from JEI breaks the connection for user)

**To Reproduce**
1. Open crafting terminal for Integrated Storage
2. Search Jukebox vanilla item in JEI
3. Attempt to craft from JEI by clicking Jukebox and clicking the "+" sign to place the resources
4. Minecraft server connection will break and disconnect user (no server side issues)

**Expected behavior**
-> Jukebox recipe should push to crafting grid in Integrated Storage

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![jukebox error](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/10853965/684cce51-0353-4fcc-940e-1c7575599249)
![crafting screen - pre error](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/10853965/8d46fd7a-0842-460d-ae01-2ad253b4bb1f)

**Modpack version**
-> 0.2.0
**Java Version** 
->8
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 12gb

**Additional context**
-> No other prominent details

**Comment by ChosenArchitect** [comment]
should be fixed in 0.2.1 as mod updated and I tested and seems to not crash when crafting

**Comment by dreadstuff** [comment]
Awesome thanks!!! :)
