### ISSUE TITLE
Mod suggestion 

### ISSUE THREAD

**Issue by vinhsangdang** [ChosenArchitect/ChosensModdedAdventure#27]
**Is your feature request related to a problem? Please describe.**
->well i want to know how mane durability my item is.

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->https://www.curseforge.com/minecraft/mc-mods/durability-tooltip

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I will add that! should be in 0.2.1
