### ISSUE TITLE
No SLF4J providers were found

### ISSUE THREAD

**Issue by RustyGentleman** [ChosenArchitect/ChosensModdedAdventure#28]
**Describe the bug**
-> Instance fails to start.

**To Reproduce**
1. Download the 2.0 version of the modpack
2. Try to launch the instance

**Expected behavior**
-> The game starts

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/14930366/2b279cb6-be3f-4db3-8bf2-1cb16779a6bf)

**Modpack version**
-> 2.0
**Java Version**
-> OpenJDK
**Modpack Launcher Used**
-> GDLauncher
**Ram Allocated**
-> 4GBs

**Additional context**
-> This used to happen before, seldom and at random times, though more often while exploring. Upon updating to 2.0, however, the game fails to even start.

**Comment by MalaChaiLatte** [comment]
Are you still having issues, If so could you update to the lastest version, post your Java Number (ex. Java 17.0.6)

**Comment by RustyGentleman** [comment]
Apparently I did not have Java itself installed. I've installed 19.0.2, and the issue seems to mostly have gone away, but it has still happened since, albeit much less frequently. It now only happens when I travel fast into unloaded chunks; the game freezes for a few moments and closes, with the launcher displaying that message.

**Comment by ChosenArchitect** [comment]
Thanks for getting back!
