### ISSUE TITLE
RF tools Builder problem

### ISSUE THREAD

**Issue by Remains808** [ChosenArchitect/ChosensModdedAdventure#29]
**Describe the bug**
->RFTools Builder will freeze on loot chest by the lootr mod

**To Reproduce**
1.  run a builder in quarry mode
2.  have a lootr chest in the quarry zone
3. 
4. 

**Expected behavior**
-> either skip over the chest or break it

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.2.0
**Java Version**
-> Curseforge Default
**Modpack Launcher Used**
-> remains808
**Ram Allocated**
-> 16gb

**Additional context**
-> you can contact me on Discord if you need. Same name

**Comment by ChosenArchitect** [comment]
should be fixed in next update! 0.2.1
