### ISSUE TITLE
Quest Book

### ISSUE THREAD

**Issue by I3lueangel** [ChosenArchitect/ChosensModdedAdventure#3]
**Describe the bug**
-> questbook empty

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Quest Book is a work in progress and will be added as soon as I am finished with it.
