### ISSUE TITLE
recipe conflict when making Polished blackstone

### ISSUE THREAD

**Issue by Remains808** [ChosenArchitect/ChosensModdedAdventure#30]
**Describe the bug**
->there are two items made by placing blackstone in a 2x2

**To Reproduce**
1. place black stone in a 2x2
2. 
3. 
4. 

**Expected behavior**
->create on recipe or the other. AE2 and Refined can not deal with double recipes like this

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->0.2.0
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This is going to happen to a lot of the recipes if you use a normal crafting table it will fix this by giving you a option to change what you are making or you can use the stonecutter.
