### ISSUE TITLE
Crashing 1-2minutes into the launch of pack

### ISSUE THREAD

**Issue by GraidGaming** [ChosenArchitect/ChosensModdedAdventure#31]
i downloaded the pack in the ATLauncher and downloaded the pack . Launched it but it wldnt launch .. tried to launch multiple times but it crashes after about 1-2 minutes into the launch.. i tried reading the latest logs but i jst cldnt find the problem. would appreciate quick and good help... 
The latest log file: 

[latest.log](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12848052/latest.log)

**Comment by ChosenArchitect** [comment]
Be sure to use the Cruseforge launcher as the ATLauncher seems to have issues downloading the modpack from curseforge.
