### ISSUE TITLE
Hoppers (and Sophisticated Barrels with Hopper Upgrades) extract fuel from Vanilla Furnace, Smoker and Blast Furnace when placed at the bottom.

### ISSUE THREAD

**Issue by tariqk** [ChosenArchitect/ChosensModdedAdventure#32]
**Describe the bug**

Vanilla hoppers normally only extract the items from the output slot (i.e. the right slot) of vanilla furnaces, smokers and blast furnaces, and don't normally touch the input (i.e. the top slot) and fuel (i.e. the bottom slot) of those machines. 

Something in the modpack appears to override this behavior, where the hoppers extract _all_ items from those machines, including fuel and input items. Is this expected behavior?

**To Reproduce**
1. Build furnace and place it in the world.
2. Put a hopper underneath the furnace, facing any direction.
3. Place fuel in furnace, or an input item into the furnace.
4. Watch the hopper drain all fuel and input items into itself.

**Expected behavior**
Per the Minecraft Wiki, on the [relevant section](https://minecraft.wiki/w/Hopper#Container_interactions) for the hopper:

> A hopper below a furnace pulls everything from the output slot and empty [buckets](https://minecraft.wiki/w/Bucket) from the fuel slot left over from using [lava buckets](https://minecraft.wiki/w/Lava_bucket) as fuel.

This behavior allows for convenient, [early-game furnace automation](https://minecraft.wiki/w/Tutorials/Automatic_smelting#Semi-automatic_furnace), which allows the player to leave the furnace running while they perform other actions, and not need to worry about providing fuel or other input items into a container.

**Screenshots**
n/a (I'm logging this issue on a different machine)

**Modpack version**
0.2.0
**Java Version**
17.0.7
**Modpack Launcher Used**
Prism Launcher, 7.2
**Ram Allocated**
6144 MB

**Additional context**
I'm running this on Linux (Pop_OS! 22.04 LTS).

**Comment by ChosenArchitect** [comment]
So updated some mods and did a check and it seems whatever I updated fixed the issue you were having
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/d675c717-902e-4bef-aacf-3f32167d4327)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/44b42f6e-292d-45e2-8347-e8649c64a7c9)

**Comment by ChosenArchitect** [comment]
fixed in 0.2.1
