### ISSUE TITLE
Crashes When I Open My Colossal Chest

### ISSUE THREAD

**Issue by joklbash** [ChosenArchitect/ChosensModdedAdventure#33]
**Describe the bug**
-> Getting Started quest named Crafting Essentials shows 100% complete when hovering over the quest. When opening the quest, it shows Wool as not complete (no checkmark) and won't allow completion. Holding wool in inventory doesn't appear to accept it.

**To Reproduce**
1. Complete the quests prior to Crafting Essentials.
2. Gather leather, wool, feather and stick.

**Expected behavior**
-> Quest should complete and give rewards.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/3988215/a17080f7-1dc3-480d-822f-2b5d3157c671)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/3988215/7555bee9-256e-4f60-857d-d4506b496502)

**Modpack version**
-> 0.2.0
**Java Version**
-> 17
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 10G

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Fixed in next update 0.2.1
