### ISSUE TITLE
Crash holding a minecraft map - ticking player

### ISSUE THREAD

**Issue by Thorton101** [ChosenArchitect/ChosensModdedAdventure#34]
**Describe the bug**
-> game crash during holding a minecraft map piece

**To Reproduce**
1. don't know - logged in my world, took the map out of a chest and game crash -> ticking player

**Expected behavior**
-> no game crash

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
n/a

**Modpack version**
-> version 0.2.0 forge-47.1.3
**Java Version**
-> curseforge standard java se development kit 19.0.1 (64-bit)
java arguments : -Xmx12096m -Xms256m -Dminecraft.applet.TargetDirectory="D:\Games\MinecraftModded\CurseForge\Instances\Chosen's Modded Adventure" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

**Modpack Launcher Used**
-> curseforge - launcher
**Ram Allocated**
-> 12096 MB

**Additional context**
-> was able to loot the map and used it 2 days ago, took it out of a chest and it landed on my hotbar slot 6.

additional info: found the map that causes the issue with the older version of the modpack
installed an additional version of the modpack version (version 0.1.3) and was able to load my world save.
Copied my world save back and was able to start the world in the 0.2.0 - version.

[crash-2023-10-10_23.43.57-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12862056/crash-2023-10-10_23.43.57-server.txt)

**Comment by ChosenArchitect** [comment]
Will keep and eye on this as I cant seem to reproduce with any map... seems like such a outside case. Thanks for the report!

**Comment by Thorton101** [comment]
Hi Cody, 

don't know, what happened. Because the map was a minecraft entity. But to reproduce it, the map was initialized in modpack version 0.1.3, deposit in a vanilla doublechest and after an update to modpack version 0.2.0 the crash happened.

best regards
Thorton

**Comment by ChosenArchitect** [comment]
Should be fixed now with Moolight LIB being updated
