### ISSUE TITLE
latest version crashes when i pick logs 

### ISSUE THREAD

**Issue by moltedjet** [ChosenArchitect/ChosensModdedAdventure#35]
me and a friend got this pack set up on our server the moment ethier of us picked up logs the pack hard crashed and gave us this error

[message.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12875488/message.txt)
 not sure if that wall of text helps 
 
 
 update im just crashing like minutes after i load into the server/world

**Comment by moltedjet** [comment]
update im just crashing like minutes after i load into the server/world

**Comment by MalaChaiLatte** [comment]
Did you update to the hotfix?

**Comment by MalaChaiLatte** [comment]
Did you update to the hotfix?

**Comment by ChosenArchitect** [comment]
issue report doent have enough information and didn't follow the template
