### ISSUE TITLE
Crashes When I Change Gamemode as Op

### ISSUE THREAD

**Issue by TBrauns** [ChosenArchitect/ChosensModdedAdventure#38]
**Describe the bug**
The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Registry Object not present: skinnedlanterns:pufferfish_lantern_block

**To Reproduce**
1. Load into a server or single player game.
2. Get OP or give yourself OP.
3. Use FTB Utils to Change Gamemode
4. Crash occurs

**Expected behavior**
->

The crash is also random at times, but this specifically will break it. I expect this to not happen.

**Screenshots**

Crash not applicable.

**Modpack version**
-> 0.2.2
**Java Version**
-> N/A
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 12gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
is there a crash log?

**Comment by TBrauns** [comment]
[2023-10-14-3.log](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12910903/2023-10-14-3.log)

**Comment by ChosenArchitect** [comment]
It seems to be an issue with the items skinned lanterns pufferfish and in testing on the new build, something might have fixed that issue as it's not crashing in my test build.
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/7293d823-0e3f-43bb-873b-4f1b537b1f54)

**Comment by ChosenArchitect** [comment]
will close for now and if issue shows up after the update ill reopen this issue till fixed
