### ISSUE TITLE
Do not show item on Refined Storage!!!

### ISSUE THREAD

**Issue by bluismine** [ChosenArchitect/ChosensModdedAdventure#40]
**Describe the bug**
-> When I put all my items on my chest into RS, all items on RS are not showable (I think the cause is some items of other mods) 
(why "not show"? when I use the JEI recipe on RS Grid Crafting, the recipe works, meaning the item is still RS)
and storage is not full, energy is full too. I think u got it!

**To Reproduce**
1.  Add many stacks of items of many mods
2. the items is not showing!

**Expected behavior**
-> Item is show on RS "again"

**Screenshots**
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/943be462-4667-44d9-866c-3f6ec871c3bc)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/1b19d117-6a9f-4c70-b9c0-5a863a62cabb)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/f05da99d-872d-48c6-b8d1-9acf0bf14d11)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/d73d0705-18a0-4b35-aca6-5f352b160d35)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/99c90fbe-5e3b-4b8a-9cde-22fc291b62d1)

**Modpack version**
-> 0.2.2
**Java Version**
-> 20
**Modpack Launcher Used**
-> 
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/110566084/17375fcf-3446-40ae-81d5-2212043ce366)

**Ram Allocated**
-> 6Gb

**Additional context**
-> ...............................

**Comment by ChosenArchitect** [comment]
Were you able to check to make sure you didn't set it to show only craftable? In my testing, I am able to see the items in the drives.

**Comment by ChosenArchitect** [comment]
also this seems to be a wireless grid... ill need to do further testing to see if this is maybe just for the wireless grids

**Comment by ChosenArchitect** [comment]
so in testing, I was able to see items in my wireless grid as well... now sure what is going on maybe try using a different drive then the 4k?

**Comment by MalaChaiLatte** [comment]
Which launcher are you using, I'll try and emulate this in within the next couple hrs

**Comment by MalaChaiLatte** [comment]
Could you also post a log file from when you accessed the terminal

**Comment by MalaChaiLatte** [comment]
@bluismine you still need help?
