### ISSUE TITLE
Game crashes when i try to open a world on Macbook

### ISSUE THREAD

**Issue by Rhiannon-Renee** [ChosenArchitect/ChosensModdedAdventure#41]
**Describe the bug**
-> I can create a world, but when I try to go in and play it, it crashes and shows error code 6.

**To Reproduce**
1. Launch
2. Let load
3. Singleplayer
4. Launch world

**Expected behavior**
-> I would like the world to load so that i can play.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
<img width="1440" alt="Untitled" src="https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/148595229/4514aed2-6843-440b-878d-3cd2dd56ce79">

**Modpack version**
-> 0.3.3 (and any version i use)
**Java Version**
-> 1.20
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->6.3 GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
So this is an issue with your graphics drivers being out of date. You need to update your graphics card drivers and this might fix the issue.

**Comment by Rhiannon-Renee** [comment]
Ive tried it many times since updating it, and it still crashes. Not sure what it could be.
