### ISSUE TITLE
Crashes When I Open My world

### ISSUE THREAD

**Issue by Levizashulker** [ChosenArchitect/ChosensModdedAdventure#42]
**Describe the bug**
-> game crashes when I try Jon a single player world

**To Reproduce**
1. Launch game
2. Wait to load
3. Create world
4. Wait to load

**Expected behavior**
-> world loads sucsefully

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> n/a
**Java Version**
-> I can't remember
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> not sure maby 4gb

**Additional context**
-> sorry this happened a little while ago like last week or something.

**Comment by ChosenArchitect** [comment]
I need to know what version of the modpack you are on and more of the info asked in the template otherwise I have nothing to go off of.

**Comment by Levizashulker** [comment]
I was playing a day after the midpack released on Curseforge, I had 4-6 gb
of ram allocated to the game.

**Comment by MalaChaiLatte** [comment]
So are you still on the pre-release version?
