### ISSUE TITLE
Server files for the Modpack

### ISSUE THREAD

**Issue by k1ngf15h3r** [ChosenArchitect/ChosensModdedAdventure#44]
Maybe I don't see it, but I can not find any serverfiles for this modpack. 

Can the client files be used as server files?

**Comment by adheydonuts** [comment]
On curseforge, to the left of play and to the right of the 3 dots there's a button. Click it and that's how you download the server files.

**Comment by ChosenArchitect** [comment]
Client files will end up crashing for the 0.3.3 you will need the server files from here: https://legacy.curseforge.com/minecraft/modpacks/chosens-modded-adventure/files/4806513

**Comment by k1ngf15h3r** [comment]
Thank you, I don't found this when I was searching through curseforge. Now I can start my adventure 😁 looking forward what you build for us 🙏
