### ISSUE TITLE
Updated to 0.3.3 and deleted the end world file, now to End portal

### ISSUE THREAD

**Issue by adheydonuts** [ChosenArchitect/ChosensModdedAdventure#45]
**Describe the bug**
->So the title says most...but when I updated the server to the newest version of the mod pack (0.3.3) there's no end portal in the end dimension. The spot where the egg normally spawns on when you kill the dragon or where you go to summon the dragon in again. 

**Expected behavior**
->What I expected to happen is delete the old world file so with the new update there'd be less corruption issues since new world generation.

**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->32

**Comment by ChosenArchitect** [comment]
This is a vanilla thing but this might help:
The "DragonFight" data lives in level.dat; if you delete it from there using an NBT editor while also deleting DIM1 then it should respawn fine.

DragonFight tracks whether there is currently a live dragon, whether a dragon has been killed in the past, which gateways are yet to generate, and where the exit portal is.
