### ISSUE TITLE
AE2 wireless issues

### ISSUE THREAD

**Issue by Remains808** [ChosenArchitect/ChosensModdedAdventure#46]
**Describe the bug**
->when using a infinity range or Dimension Card for wireless AE you can only take out/put in a maximum of 32 items

**To Reproduce**
1. create AE system
2. install either card
3. try to remove a stack
4. 

**Expected behavior**
->be able to move a stack of items simular to Refined storage

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->since 2.0 for sure but currently 3.3
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
-> I have added 20 stacks superdense energy cells and connected a creative power source to see if it was a AE power limitation however no change

**Comment by ChosenArchitect** [comment]
This is a known issue and currently, there isn't a full fix yet outside of someone who pushed a jar but the mod dev still hasn't fixed it! Once a fix in out this will be updated.
https://github.com/Hexeption/AEInfinityBooster/issues/14

**Comment by ChosenArchitect** [comment]
should be fixed in the latest version
