### ISSUE TITLE
Falling into the void infinitely [Crash/Bug]

### ISSUE THREAD

**Issue by Shadow-355** [ChosenArchitect/ChosensModdedAdventure#48]
**Describe the bug**
Upon launching the world, the player is at -70 and begins to fall through the void endlessly. Attempts to use commands to teleport or kill the player don't function. When attempting to Save and Quit from this state, the game will hang on the "Saving world" screen. The tips continue to scroll, so it's not frozen, but it just refuses to save and quit usually requiring the task manager to kill the process.

**To Reproduce**
1. Launch Single Player World

**Expected behavior**
-> The world should launch and place the character at the correct saved position.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2023-10-23 13_07_50-Window](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/60007620/99657e46-a92c-4db9-94de-50ed4253ab6c)
![2023-10-23 13_10_42-Window](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/60007620/9ad6f59d-7fc7-4167-8507-d0bd4940b498)

**Modpack version**
-> 0.3.3
**Java Version**
-> forge-47.1.3 - 1.20.1
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 12GB

**Additional context**
This issue has occurred before on other versions, but after a couple of tries, I've always been able to get back into the world generally at some point. The past six or seven times I've tried lately have been unsuccessful. /spawn and /home also don't work properly.

**Comment by Avalonzo** [comment]
This sounds a lot like the problem I was having can you check your mods folder and see if nomowanderer-1.20.1_1.6.0.jar is still present if so delete it and as it was meant to be removed in the 0.3.3 update. When I updated I still had it and deleted it manually and all my freezing, commands and save and quit started working after that.

**Comment by Shadow-355** [comment]
That mod isn't present in my mods folder, is there some other place I need to delete it from?

**Comment by MalaChaiLatte** [comment]
Can you send a log file please, and add your java version, (ex. 17.0.8)

**Comment by Shadow-355** [comment]
This is the only crash file that was generated from the situation.
[crash-2023-10-24_17.48.17-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13140475/crash-2023-10-24_17.48.17-client.txt)

As for the Java version, I believe it's 1.8.0_332 unless I'm looking in the wrong place.

**Comment by Shadow-355** [comment]
Some additional data has come up as well. I tried swapping my forge version from 47.1.3 to 41.2.1 to see if that would help, it didn't.
Additionally, I noticed if I load the world and touch nothing on the keyboard, my character will appear in the correct coordinates, but all the blocks will be invisible around me, though the outline could be seen when I moved the cursor around. I was able to move around the world, and after jumping I started falling through the world again, so it appears something is making the blocks act like they don't exist to the player? I could also see particles, (torch particles). I could try to get another screenshot of this particular instance if it will help.

**Comment by Shadow-355** [comment]
I've done a bit more troubleshooting since I've had some free time.

I have no problems creating new worlds, they function as expected.
I've attempted to roll back my world using backups, (I create a backup every time I exit the world.) I found a backup from Oct 18th that appears to work without issue, while my latest backup on Oct 22nd isn't working.

I can provide the world downloads if it'll help to diagnose the issue. I'm uncertain what is different between those four days that could be causing the issue.

**Comment by MalaChaiLatte** [comment]
If you could provide those, that would be helpful, I'm looking into the crash reports now

**Comment by MalaChaiLatte** [comment]
Did you use framed blocks?

**Comment by Shadow-355** [comment]
Framed blocks? No, I don't believe I have used any of those in this world.

Since the worlds are too big to upload here, I've created a Google Drive link for both worlds. The "Shadow's Adventure" is the current world, and the one labeled "10-18..." is the backup.
https://drive.google.com/file/d/1leZDu1TewTmTxaxWM8WfrA3Jh1N_hF4r/view?usp=sharing
https://drive.google.com/file/d/1v0x0jQzHHp1aXeWREqc-lMP1IQBIa4zn/view?usp=sharing

**Comment by MalaChaiLatte** [comment]
Cool, I'll look at them in a couple hrs, got some school stuff rn.

as for the framed blocks, that's odd considering that this is in the log:

Recovery reason: java.util.concurrent.CompletionException: net.minecraftforge.fml.ModLoadingException: FramedBlocks (framedblocks) encountered an error during the enqueue_imc event phase

**Comment by MalaChaiLatte** [comment]
Just to confirm, have you added any mods?

**Comment by MalaChaiLatte** [comment]
I mangaged to log in fine, Could you try java 17?


![Screenshot 2023-10-25 at 14 20 16](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/114491463/374362a2-160c-4a13-a769-35bcc17da574)

**Comment by Shadow-355** [comment]
I logged in to check, and this is the debug screen I'm getting. I'm running Java 17.0.8, and it appears that the chunks themselves are having issues loading.
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/60007620/b15e1160-c519-4e3a-a917-acdfd805e8f0)

**Comment by MalaChaiLatte** [comment]
Are you on windows or mac?

**Comment by Shadow-355** [comment]
Windows 10 specifically

**Comment by MalaChaiLatte** [comment]
Your world works perfectly on my system lol.

**Comment by MalaChaiLatte** [comment]
You havent added mods?

**Comment by Shadow-355** [comment]
No, I haven't. I'm going to try completely deleting the entire modpack and reinstalling it, to see if that fixes it.

**Comment by MalaChaiLatte** [comment]
Yea, thats odd.

the next thing I would suggest if that fails is 
1. try removing your player data
2. try java 17.0.6 specificaly
3. try a different launcher such as prism

**Comment by Shadow-355** [comment]
An update:
Reinstalling the modpack didn't fix the issue.
Removing the player data didn't fix the issue.
Using Prism Launcher 7.2 with Java 17.0.6 didn't fix the issue.

I did, however, get a boatload more information through Prism's log.
[ShadowsAdventureBugLog.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13160594/ShadowsAdventureBugLog.txt)

**Comment by MalaChaiLatte** [comment]
I'm out of ideas, @ChosenArchitect you wanna jump in?

**Comment by MalaChaiLatte** [comment]
Could you try just leaving the world loading until the log stops moving for 5 minutes

**Comment by MalaChaiLatte** [comment]
If that fails, I'll send you your world file from after I loaded in, as I noticed my game modified some of your configs.

**Comment by Shadow-355** [comment]
It's just super weird that my world works totally fine for you, but completely fails on both Curseforge and Prism for me. I'll try leaving the game running for several minutes, both in the "falling" state, and the "saving world" state to see if it crashes properly or fixes something.

I would be _very_ curious to see if the world works after you send it back, which means there has to be a config or setting that's causing the issue.

**Comment by MalaChaiLatte** [comment]
Heres the world file, 
[https://drive.google.com/file/d/1Y6FKjWSqkm6RmguaowYS2_3b-gBURXCU/view?usp=sharing](https://drive.google.com/file/d/1Y6FKjWSqkm6RmguaowYS2_3b-gBURXCU/view?usp=sharing)

**Comment by Shadow-355** [comment]
:( The world you sent me didn't work. I'm all out of ideas. I don't mind starting over, but I'm really worried it'll happen again after who knows how long. Maybe it's my computer? I have no idea how my computer would be having issues with it, and it's a pretty fresh OS. I've got nothing.

**Comment by Shadow-355** [comment]
I very much appreciate all the help you've given me so far, it's been very helpful! I thank you for helping out.
