### ISSUE TITLE
Crashes When I try to start my server 0.3.4 with Shockbyte Hosting

### ISSUE THREAD

**Issue by SoulfulMarch** [ChosenArchitect/ChosensModdedAdventure#49]
**Describe the bug**
->Worked in previous versions after updating to 0.3.4 the server won't even begin to load and crashes within 10 seconds on start up.

-> the server console feed after starting it up if anyone understands it.

-> Just copied the new files over after deleting, the mods, scripts, configs, and default configs. I can switch back to the previous version from my saved files with no difficulty

26.10 18:53:46 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
26.10 18:53:46 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.1 by Oracle Corporation; OS Linux arch amd64 version 4.19.0-18-amd64
26.10 18:53:47 [Server] INFO Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.util.zip.ZipException: invalid END header (bad central directory offset)
26.10 18:53:47 [Server] INFO Caused by: java.util.zip.ZipException: invalid END header (bad central directory offset)
26.10 18:53:47 [Server] INFO 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1544)
26.10 18:53:47 [Server] INFO 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:174)
26.10 18:53:47 [Server] INFO 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
26.10 18:53:47 [Server] INFO 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
26.10 18:53:47 [Server] INFO 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
26.10 18:53:47 [Server] INFO 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:475)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:136)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
26.10 18:53:47 [Server] INFO 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:76)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:48)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:38)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
26.10 18:53:47 [Server] INFO 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
26.10 18:53:47 [Server] INFO 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
26.10 18:53:47 [Server] INFO 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
26.10 18:53:47 [Multicraft] Server shut down (starting)
26.10 18:53:47 [Multicraft] Restarting crashed server in 10 seconds
26.10 18:53:47 [Multicraft] Looks like a crash, check the server console. Return value: 1
26.10 18:53:47 [Multicraft] Server stopped
26.10 18:53:50 [Multicraft] Received stop command
26.10 18:53:50 [Multicraft] Server stopped

**Comment by ChosenArchitect** [comment]
Did you make sure you accepted the EULA?

**Comment by SoulfulMarch** [comment]
I opened Eula.text and it is set to true

**Comment by SoulfulMarch** [comment]
Error fixed, some sort of mod discrpancy was causing issues so I deleted them all and redownloaded them all. 
server is now running.
thanks for your help!
