### ISSUE TITLE
When an entity (including players) stands on a bed or is in the air they get dragged to the ground very fast

### ISSUE THREAD

**Issue by C0nlan4** [ChosenArchitect/ChosensModdedAdventure#50]
**Describe the bug**
->When standing on a bed this glitch causes your avatar or any entity to jump and if you are falling the glitch causing the speed you are falling at the increase.

**To Reproduce**
1. Stand on the bed or jump into the air
2. Get dragged towards the ground
3. (Usually happens when i have a crafting table on a stick in my inventory)
4. (Note: Doesnt always happen, its just been a few rare cases for me)

**Expected behavior**
->Not to get dragged into the void at the speed of light

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->First release                 (Chunk by Chunk)
**Java Version**
->17.0.8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10176MB

**Additional context**
->Doesnt always happen

**Comment by ChosenArchitect** [comment]
You were experiencing a tiny moon this has a chance of happening every night but a small one. It's from the lunar mod. It also say it in chat. There are many moons that can happen and each cause a different effect.
