### ISSUE TITLE
Falling into the void for a second time make you lava resistant until you stand on a block

### ISSUE THREAD

**Issue by C0nlan4** [ChosenArchitect/ChosensModdedAdventure#52]
**Describe the bug**
->falling into the void for a second time make you lava resistant until you stand on a block

**To Reproduce**
1. Jump into void
2. wait until you are teleported back into the sky
3. land in flowing lava 
4. Become temporarily lava resistant

**Expected behavior**
->die to lava because of lava damage

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->First release (Chunk by Chunk)
**Java Version**
->17.0.8
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->10176MB

**Additional context**
-> N/A

**Comment by ChosenArchitect** [comment]
Does this effect wear off? I know that lava would normal kill you due to fall damage but the forgiving void mod might be causing that for that reason
