### ISSUE TITLE
World Forge crashes when you keep a Cobble Gen5 for too long

### ISSUE THREAD

**Issue by ItsJustReeses** [ChosenArchitect/ChosensModdedAdventure#53]
**Describe the bug**
Kept a Cobble Gen 5 + Gold Hopper + World Forge and didn't check on it for a while Noticed at one point I was at 64 World Cores but didn't take them out. Came back a few hours later as I needed them and when I right clicked on the World Forge my game crashed.
->

**To Reproduce**
1. Place a Cobble Gen 5 above a golden hopper
2. Have hopper filter into World Forge
3. Wait a few hours for it to exceed 64 World Cores
4. Right click on World Forge

**Expected behavior**

-> Expected it to stay at 64 world cores and be officially "full" but I believe it tries to keep going.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> Release version
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Forge
**Ram Allocated**
-> 16

**Additional context**
-> May be good to potentially nerf these as well as getting a Cobble Gen5 is pretty easy to do. Making an abundant amount of Worldstone Cores

**Comment by ChosenArchitect** [comment]
If you have the crashlong that would be nice so I can send this to the mod dev

**Comment by Lythenas** [comment]
I think I ran into the same error. I'm on modpack version 0.1.3. Here is the crash report I got: https://mclo.gs/s6ysyKH

Just for the record. Breaking the world forge drops the stack of world cores and stack of cobble and does not crash.

**Comment by Bubbyd81** [comment]
[crash-2023-11-09_07.22.06-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13307997/crash-2023-11-09_07.22.06-client.txt)I'm having the same issues. What will be the best way to fix this so that I can use the forge again ? I have taken the gen 5 cob off and it still crashes.

**Comment by Lythenas** [comment]
@Bubbyd81 just breaking the world forge worked for me. I then put a drawer with a hopper upgrade under it, so it just pulls out the world cores. Hasn't crashed after that.

**Comment by ChosenArchitect** [comment]
Another ref - https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/76
