### ISSUE TITLE
Crashes in the Nether

### ISSUE THREAD

**Issue by arrisiane** [ChosenArchitect/ChosensModdedAdventure#54]
The nether is also a chunk by chunk and i loooooove that. But after just a very short while , 1-5 minutes i crash out with the following error for some reason: 

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "data.lootId" is null

**Comment by arrisiane** [comment]
[crash-2023-10-31_15.16.54-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13217526/crash-2023-10-31_15.16.54-server.txt)

**Comment by arrisiane** [comment]
Since i visited the Nether , i get this error even when being in the overworld

**Comment by arrisiane** [comment]
Update : Removing Nethers Overhaul fixed the issue for me

**Comment by ChosenArchitect** [comment]
what version of the modpack are you on as as version 0.1.1 should have a updated nether overhaul that might fix this

**Comment by arrisiane** [comment]
I was on the latest : 0.1.1

**Comment by Clonephaze** [comment]
> I was on the latest : 0.1.1

The latest when this was posted was 0.3.4 though, and now it's 0.3.5
