### ISSUE TITLE
Unable to use certain balance stone recipes

### ISSUE THREAD

**Issue by KamitoMito** [ChosenArchitect/ChosensModdedAdventure#55]
**Describe the bug**
->When using the 'balance stone' I am able to make a diamond into an emerald, but not the other way. 

**To Reproduce**
1.  N/A
2. 
3. 
4. 

**Expected behavior**
->When using a balance stone together with 1 emerald I expected to be able to craft 2 diamonds.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Unable to craft diamodn](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149505788/f4975731-4434-4ee4-bac1-472ebb0838d3)

**Modpack version**
-> 0.3.4
**Java Version**
-> I don't nkow
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
So this was a thing that was available and I made the choice to remove this and really limit what can be done with this to better balance the stone. This is intended.
