### ISSUE TITLE
Interacting with Trader block (Easy Villagers) Crashes

### ISSUE THREAD

**Issue by atoldiago** [ChosenArchitect/ChosensModdedAdventure#57]
**Describe the bug**
Attempt to right click the Trader block to trade (Easy Villagers) crashes the game. Its important to note, this is happening on any Trader block, but started after I swapped villagers and profession blocks out of a Trader block twice. Was only using one, swapped twice, and now they all crash (I now have three, for example).
->

**To Reproduce**
1. Use one Trader block, place Villager with profession and its profession block. Trade.
2. Swap with a different Villager and its profession block. Trade.
3. Swap back to previous Villager and profession block, attempt to trade. It crashes (for me).
4. Create new Trader blocks, fit each villager into their own. Attempt to trade. It crashes (for me).

**Expected behavior**
-> I expect to be able to trade with whatever villager is in the Trader block, regardless how many times I swap the villager out.

**Screenshots**
Screenshot of Error given:
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/69121652/672e7466-aac5-4c5a-9533-046dfb9b3012)

**Modpack version**
->CMA Chunk by Chunk-0.1.2
**Java Version**
-> I have no idea, and cant find it anywhere (no method Ive found to locate it works)
**Modpack Launcher Used**
->Curseforge (latest version as of this post)
**Ram Allocated**
->Just over 9g

**Additional context**
->Can provide crash report if needed

**Comment by atoldiago** [comment]
Breaking and placing the Trader block with villager and profession block still in it didnt change anything. Breaking and placing the originally offending Trader block without anyone or anything in it didnt change anything. Do those two actions, with new villagers, didnt change the outcome either. Figured after all that (I didnt add those steps in because that was my own attempt at basic troubleshooting that likely wont reveal anything new to help), its probably time to come here.

**Comment by atoldiago** [comment]
Okay so theres a change: I didnt realize I was wearing the 'Discount Voucher' accessory while doing this. I just took it off, and the villagers work again. Im not sure what to make of it, other than the issue is the accessory, not the Trader block.

**Comment by ChosenArchitect** [comment]
should be fixed in next update
