### ISSUE TITLE
Hit by zombie now i have slowness for 3 hrs and -4 attack damage for 3 hours.

### ISSUE THREAD

**Issue by SkullbasherJ** [ChosenArchitect/ChosensModdedAdventure#58]
**Describe the bug**
-> built a zombie mob spawner with 3 different spawners. was hit by a zombie and now i have 3hrs of slowness and decreased attack damage. i cant move unless i'm jumping and sprinting. and its only as far as i can jump is how i move. i also have jump boost for 3 hours and my Field of view is zoomed in. zombies are also coming out of a spawner with 138 hours of fire resistance
![2023-10-31_21 01 12](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/012059b6-0988-4f8d-a9ac-811b1d45f8ad)
![2023-10-31_21 01 17](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/8f695d8e-f037-495a-85d1-5e4821161487)
![2023-10-31_21 01 22](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/7484b4a2-cb76-4520-b11c-20f99f9d9e8c)
![2023-10-31_21 01 30](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/6993300b-c19b-4f5d-9ffb-c9fb1a67e2ef)
![2023-10-31_21 01 57](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/591f6f96-6fb3-4fd6-a10a-7bca399c4c63)

**To Reproduce**
First time happening and still waiting for the timer to get to zero to be able to play

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.3.4
**Java Version**
->
**Modpack Launcher Used**
-> cursed forge
**Ram Allocated**
->

**Additional context**
->

**Comment by Clonephaze** [comment]
Just as a fix for your timer issue, can you spawn in a bucket of milk and drink it? It would be `/give @s minecraft:milk_bucket`. If cheats are not enabled on your single player world then pause the game, click  "Open to LAN" and "allow cheats" to "on" then "Start LAN World", then run the command. 

Also, what kind of spawner are you using to spawn the zombies? Apotheosis, Enderio powered spawner, industrial forgoing spawner etc?

**Comment by SkullbasherJ** [comment]
> Just as a fix for your timer issue, can you spawn in a bucket of milk and drink it? It would be `/give @s minecraft:milk_bucket`. If cheats are not enabled on your single player world then pause the game, click "Open to LAN" and "allow cheats" to "on" then "Start LAN World", then run the command.
> 
> Also, what kind of spawner are you using to spawn the zombies? Apotheosis, Enderio powered spawner, industrial forgoing spawner etc?

-----------------------------------------------------------------------------------------------------------------------------------------

Im gunna say apotheosis. they were spawners i found in the world and silk touch collected. they only say Minecraft.
I didn't know about being able to swap to allow cheats that way. i sat there for the full time collecting XP lol. XD
but i couldn't move because the slowness said -15% but in the little feed back thing said over -3000 speed.

![2023-11-01_00 32 05](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/149546843/03568a23-b3e9-4a01-a020-2796c6e73c68)

**Comment by SkullbasherJ** [comment]
I commented on Chosen's Youtube video the other day. He was saying he needed a bug report. I'm not sure if there is anything else i can do so that this 3 hrs of no movement doesn't happen to anyone else. i can see this be a mood killer for people that are doing a lot n game and then boom 3 hrs of being stuck or if someone is just starting out and get hit while exploring.

**Comment by ChosenArchitect** [comment]
So im trying to find out whats the issue is here and I think that maybe adding attribute fix will fix this strange issue.
