### ISSUE TITLE
Warden in the containment jar isn't dropping items

### ISSUE THREAD

**Issue by Breadchan777** [ChosenArchitect/ChosensModdedAdventure#59]
I am using the lasting version of CMA (0.3.5) once I put down the jar I would occasionally get the animation of stuff being pulled out but when checking there is nothing. I trying testing it by it self and nothing, but I have noticed that when I check the drops of the warden it only shows the skulk catalyst.

**Comment by Clonephaze** [comment]
The drops of a mob like the Warden would likely be hardcoded in the game's code to drop only on death, similar to the Wither, so it won't work for a drygmy farm. Drops could still be added or modified using data packs and work for drygmys I believe, but don't qoute me on that.

**Comment by ChosenArchitect** [comment]
They no longer drop items as that was fixed in a version after I recorded my video!
