### ISSUE TITLE
Mod Suggestion: Mob Loot Blocks and maybe Pedestals

### ISSUE THREAD

**Issue by Mowmaster** [ChosenArchitect/ChosensModdedAdventure#6]
**Is your feature request related to a problem? Please describe.**
->Looking through the modlist I noticed there is a few holes, or at least not a lot of options for a few tasks i feel these mod suggestions could fill/complete for the pack.

**Describe the solution you'd like**
->
1. Mob Loot Blocks are similar to soulshards when paired with pedestals Material Generator, EXCEPT it makes a very passive way to get mob loot that is effected by enchanted tools, For a builder pack this is ideal, and if you want, there is a config in MLB to make obtaining them even easier, they also function just like mob spawn eggs, In a quest pack, they could also be used as rewards, ways to get either the mob, or its drops (or to be used to chance a spawner), OR it could be used as a quest, to obtain (as the drops for them can be configured to be rare and so they could be end game quests for killing specific mobs.)
2. Pedestals Material Generator by default could generate a plethora of blocks for those looking to just build, the regeneration rate initially is slow, but can easily be increased.
3. Pedestals fertilizer can be used for more then just crops, it can tick any randomly ticking blocks, GeOre/Amethyst could be made quicker, Dripstone for lava gens, speed up the spread of grass, mycelium, etc, and of course any crop/plant can grow faster.

**Describe alternatives you've considered**
-> 1. The only mod similar to MobLootBlocks would be Ars, which limits your mob drops where as MLB would hit the full loot table allowing for custom mob drops to still drop, outside of this, I didnt see any server friendly way to generate mob loot.
2. Cobble for Days also kinda is similar to the Material Generator, but in a limited way, Create + Vanilla mechanics can also be used but that could also be not server friendly to use, and also limited options for what to generate.
3. Modular routers, in a sense is the 'tech' version of pedestals, so this mod would be the main overlap with pedestals in the pack, Mob Grinding Utils as well covers mob farms reasonably, but pedestals still has benefits these others dont cover.

**Mod Sugestions**
->
Mob Loot Blocks: https://www.curseforge.com/minecraft/mc-mods/mob-loot-block
Pedestals: https://www.curseforge.com/minecraft/mc-mods/pedestals

**Additional context**
->
For Mob Loot Blocks, i think this image best describes how these differ and are better then other passive loot gen options since they take into account the enchants on the weapon when the block is broken (in this case, using a fire aspect sword to get cooked pork chops)
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/10681506/eaed8993-de34-4824-9ef4-481b8b7caa68)
this next image is just an ingame tooltip for one of the blocks, so it should be easy enough for any new players to use
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/10681506/b9e0168d-808e-45ad-90ff-61fa3b1da095)

**Comment by ChosenArchitect** [comment]
Still thinking about adding Pedestals! you know I love your mod <3
