### ISSUE TITLE
Crash when trading with villager with an accessory in my pocket 

### ISSUE THREAD

**Issue by Thorton101** [ChosenArchitect/ChosensModdedAdventure#60]
**Describe the bug**
->
Crash happens when trading with discount voucher - accessory in my pocket curio slot with 
villager residing in their trader from the EasyVillager - mod. 
I received that accessory via trading with villagers and swapped it with my lucky rock accessory
I usually wear.

**To Reproduce**
1.  put on discount voucher from majrusz's accessories - mod
2.  start trading with a villager inside a trader (sometimes no crash happens on the first try, but at
the second try)

**Expected behavior**
-> no crash

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 0.3.5 on forge-version forge-47.1.3
**Java Version**
-> java SE developement kit 19.0.1 (64-bit)
**Modpack Launcher Used**
-> curseforge - launcher
**Ram Allocated**
->12096 MB

**Additional context**
-> crash logs of 2 crashes
[crash-2023-11-01_14.55.33-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13227983/crash-2023-11-01_14.55.33-client.txt)

[crash-2023-11-01_15.08.04-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13227984/crash-2023-11-01_15.08.04-client.txt)

**Comment by Clonephaze** [comment]
Same thing as #57

**Comment by ChosenArchitect** [comment]
should be fixed in next update
