### ISSUE TITLE
Duplicate XP with Hero Medaillon and XP Obelisk

### ISSUE THREAD

**Issue by shinraQ** [ChosenArchitect/ChosensModdedAdventure#62]
**Describe the bug**
-> well basically the title, you can duplicate xp extremely fast, i somehow found out randomly while searching for a better way to store xp (then Hero Medaillon)

**To Reproduce**
1. Have XP on you (and Medaillon? mybe)
2. Put all your xp in Obelisk
3. Retrieve some and change Medaillon to drain xp
4. Medaillon will have now duplicated xp
5. Repeat

**Expected behavior**
->  it shouldnt duplicate the xp

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game) 

**Modpack version**
-> newest
**Java Version**
-> dont knowy not on PC rn
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 8gb

**Additional context**
-> Prob medailon didnt detect the change of xp on you, and it thinks that you still have the same amount as before, therefore that 1 level it drains will have the same amount of xp as you had previously

**Comment by ChosenArchitect** [comment]
I will need to report this to the mod dev and I hope that they know the issue

**Comment by ChosenArchitect** [comment]
Temp fixed pushed in next update
