### ISSUE TITLE
Abnormal wandering trader spawn

### ISSUE THREAD

**Issue by Nyranja** [ChosenArchitect/ChosensModdedAdventure#64]
I'm playing the modpack on a server with 2 friends atm, version 1.20.1, and whenever we sleep / a new day starts, a wandering trader appears. For each of us. So we have at least 3 running around each day - which then multiply because they don't despawn fast enough. Our maximum was 14 running around our place at the same time, two of them Plague Doctors.
I've tried to look through the configs to reduce that, also tried the no soliciting altar from the cylic mod, but they continue to spawn and it's getting extremely annoying.

If anyone knows how to reduce it / knows which config to access, please do let me know, because it's driving us insane.

**Modpack version**
-> Chosen's Modded Adventure 0.3.5
**Modpack Launcher Used**
-> Curseforge

**Comment by ChosenArchitect** [comment]
Added back Nomowanderar so this should no longer be a issue :D
