### ISSUE TITLE
Game crash due to Time in a Bottle

### ISSUE THREAD

**Issue by Kylar1014** [ChosenArchitect/ChosensModdedAdventure#65]
After updating client and server to 0.3.6., I attempted to enter creative via the inventory screen button in the upper left corner and the game crashed citing an issue with Time in a Bottle. Upon reloading the pack, just opening the inventory was enough to crash the game. This bug was confirmed on a separate instance on a separate computer.

**Expected behavior**
Game doesn't crash and user is able to toggle creative using the aforementioned button.

**Modpack version**
0.3.6.

**Java Version**
17.0.8.
**Modpack Launcher Used**
Curseforge
**Ram Allocated**
12G

**Additional context**
I attempted this in both single player and on my server. I could not duplicate it in SP. I'm available in your Discord if you want to discuss in more detail: Kylar1014

**Comment by ChosenArchitect** [comment]
do you have a crash log as that would help me send this to the mod dev

**Comment by Kylar1014** [comment]
Here you go. The crashlog is client side-only as the server did not crash.
https://hastebin.com/share/atesisekek.php

**Comment by ChosenArchitect** [comment]
Tested in latest version in creative and couldn't get this to happen so I hope it in fixed
