### ISSUE TITLE
Breaking any Spawner gives you two EIO Broken Spawners instead of just one

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/ChosensModdedAdventure#66]
**Describe the bug**
Breaking any spawner gives an extra EIO Broken Spawner item, where it should give only one.

**To Reproduce**
1. Find a monster spawner
2. Break it
3. Receive 2 broken spawners of its type

**Expected behavior**
When breaking a spawner, it should drop only one EIO Broken Spawner

**Modpack version**
0.3.6
**Java Version**
17.0.8
**Modpack Launcher Used**
Prism
**Ram Allocated**
4gb

**Comment by ChosenArchitect** [comment]
This is because EnderIO is in a beta is this is on their issue tracker
