### ISSUE TITLE
Crashes When I Use Structure Compass

### ISSUE THREAD

**Issue by vinhsangdang** [ChosenArchitect/ChosensModdedAdventure#68]
**Describe the bug**
->just bassicly use the compass (shift+right click) then minecraft crashed.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->0.3.6
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Do you have a crash log?
