### ISSUE TITLE
Placed Torches/Lanterns do not stack with those which have never been placed

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/ChosensModdedAdventure#69]
**Describe the bug**
Placed Torches and Lanterns, when broken and picked up again, don't stack with Torches or Lanterns that have never been placed before

**To Reproduce**
1. Craft multiple Torches/Lanterns
2. Place a Torch/Lantern
3. Break the light block you just placed
4. See it not stack with the others anymore

**Expected behavior**
Torches and Lanterns should stack no matter whether they have been placed before or not

**Screenshots**
![2023-11-07_06 04 17](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/32804557/5850d12c-7ed5-4ad2-a5bf-f4f2a6a7ea00)

**Modpack version**
0.3.6
**Java Version**
17.0.7
**Modpack Launcher Used**
Prism
**Ram Allocated**
4gb

**Additional context**
I installed a custom player model mod (Figura) visible in screenshot, but it is exclusively clientside and does not cause this behavior

**Comment by Gronglegrowth** [comment]
It seems to only happen sometimes, but I cant yet determine under what conditions

**Comment by ChosenArchitect** [comment]
try as I might I cant seem to get this to happen to me...

**Comment by JTurner-Portfolio** [comment]
Not sure if I should comment here or make a new issue, but I just wanted to chime in that I'm also having the same issue in both CMA and the chunk by chunk version. Advanced tooltips isn't showing any tag differences. Dropping the two stacks that aren't combining seems to temporarily clear whatever issue that occurred and allow them to combine.

**Comment by jinkhya** [comment]
Hello,
Found the mod causing this, by process of elimination.
It's been reported already : <https://legacy.curseforge.com/minecraft/mc-mods/create-stuff-additions/issues/34>
Culprit is Create Stuff and additions. That mod also add the empty tag when you claim a reward from quests. (you can see the item in your offhand move in the background when you claim, indicating the item has changed)
