### ISSUE TITLE
Infinite duplication of redstone using EnderIO or Integrated Dynamics

### ISSUE THREAD

**Issue by JARTLEON** [ChosenArchitect/ChosensModdedAdventure#7]
**Describe the bug**
You can craft 4 redstone dust into 1 Raw redstone block that can be grinded into more than 4 redstone dust.
This way you got infinite redstone consuming only FE.
->

**To Reproduce**
1. Craft 4 redstone dust in a 2x2.
2. Add the block to Sag mill or Mechanical squeezer.
3. Repeat and profit.
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Ill take a look and see whats adding that 2x2 redstone craft and see what I can do with crafttweaker

**Comment by JARTLEON** [comment]
The mod is called "Regions unexplored".

**Comment by ChosenArchitect** [comment]
Shoud be fixed in version 0.0.4 beta! Thanks for the good bug report :D
