### ISSUE TITLE
[Conflict Recipes] Conflict output between some item that have the same recipe

### ISSUE THREAD

**Issue by realkhoa** [ChosenArchitect/ChosensModdedAdventure#70]
**Describe the bug**
Conflict recipe between ALL GEAR of Industrial Foregoing and RINGS of The Aether

**To Reproduce**
1. Have a full system of Refined Storage with Crafter.
2. Open Pattern Grid
3. Search for Iron Gear recipe in JEI
4. Click the "+" icon
5. The recipe of the gear replaced by the Iron ring

**Expected behavior**
I need the encoded recipe is iron gear instead of iron ring

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
-> JDK 20
**Modpack Launcher Used**
-> Cùeorge
**Ram Allocated**
-> 8GB

**Additional context**
In regular crafting grid, like Crafting table, if i shuffle the recipe it randomize between 2 output all the time

**Comment by realkhoa** [comment]
https://drive.google.com/file/d/19BeDCJHuQ7aKmNBDvXg0NMaMq2aO_oRq/view?usp=sharing

**Comment by ChosenArchitect** [comment]
if your craft this in a normal crafting table until I fix this it will let you choose what ones you want to craft

**Comment by ChosenArchitect** [comment]
Will be fix in next update both modpacks
