### ISSUE TITLE
Make Occultism crusher spirits able to process Create's Zinc

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/ChosensModdedAdventure#71]
**Is your feature request related to a problem? Please describe.**
If one were to attempt to do ore processing entirely through Occultism's crusher spirits, one would find they can't work with Zinc, making that resource more limited before one sets up generation for it.

**Describe the solution you'd like**
The occultism crusher spirits should be given recipes to process zinc into either a new Zinc Dust item, or Create's Crushed Zinc.

**Comment by ChosenArchitect** [comment]
fixed in next update!
