### ISSUE TITLE
Crushed Silver has no Uses

### ISSUE THREAD

**Issue by CubicOwl** [ChosenArchitect/ChosensModdedAdventure#72]
**Describe the bug**

-> Silver ore from Occultism has no uses after crushed in the Create Crushing wheel

**To Reproduce**
1. Get raw Silver
2. Crush it in the Create Crushing Wheel
3.  Nothing can be done after this
4. 

**Expected behavior**

-> To be able to turn it to nuggets when washed like most other ore

**Modpack version**
-> 0.3.7
**Java Version**
-> Unsure
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 16GB

**Comment by ChosenArchitect** [comment]
Added in next update!
