### ISSUE TITLE
Geore Nouveau Too OP

### ISSUE THREAD

**Issue by beltimas** [ChosenArchitect/ChosensModdedAdventure#73]
Playing a Hosted server, with FTB Util chunks force loaded, Geore Nouveau made almost 10 stacks of every material there was in like 30 minutes so we had to remove it for the game to not be ruined by such a sudden overload in materials. I don't see how it could be a glitch but its possible so i'm not sure if they're overproducing somehow but if not maybe change the crystal fragments to be not 1:1 ratio with ingots/gems, rather maybe 9 fragments make one ingot/gem

**Comment by ChosenArchitect** [comment]
Well this is what happens when you run things on a server and load chunks. This will happen to anything that's automated and running non stop for several HOURS
