### ISSUE TITLE
Using Building Gadgets block swapper on chiseled connecting smooth Calcite corrupts the world

### ISSUE THREAD

**Issue by LastDutchHero** [ChosenArchitect/ChosensModdedAdventure#74]
**Describe the bug**
-> I tried using a Building Gadgets block swapper on some Create : Rechisled smooth connecting calcite (I believe that was it i don't exactly remember the full name) and as soon as i shift-right-clicked it it bricked up my world and crashed the entire game. Error file included. 
[crash-2023-11-12_23.46.42-client.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13329388/crash-2023-11-12_23.46.42-client.txt)

**To Reproduce**
1. Get some smooth connecting calcite
2. use block swapper on said block
3. Voila, game crash and world corruption!

**Expected behavior**
->A crash followed up by you getting kicked to main menu. Includes world corruption aftherwards

**Screenshots**
N.A.

**Modpack version**
-> 0.4.0
**Java Version**
-> 1.8.0_391 (?) Architecture 86x
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->8640MB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
There was a bug with embedium and I think it should be fixed in the 4.1 version

**Comment by LastDutchHero** [comment]
> There was a bug with embedium and I think it should be fixed in the 4.1 version

Ill check later today if it works again

**Comment by LastDutchHero** [comment]
Yep seems like that has fixed it. World is no longer corrupted, tnx!
