### ISSUE TITLE
Crash after update to version 0.4.0 in singleplayer world

### ISSUE THREAD

**Issue by Thorton101** [ChosenArchitect/ChosensModdedAdventure#75]
**Describe the bug**
-> Game crash on logging in to one of my existing world after updating to latest version of the modpack.
quote from the crash-log: 
Description: Encountered exception while building chunk meshes

Crash info from minecraft launcher:
The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.ArrayIndexOutOfBoundsException: Index 33 out of bounds for length 27

**To Reproduce**
1. update to latest version of modpack
2. try to start my main world

Mods deactivated, cause I don't like:
- creeperoverhaul
- Difficult Caves
- endermanoverhaul
- Lunar
- Nether's Overhaul
- Raided
- realmrpg_dragon_wyrms

Mods added:
- pocketstorage

**Expected behavior**
-> updating and keep playing my session

**Modpack version**
-> Chosen's Modded Adventure-0.4.0.zip
**Java Version**
->java version 17.0.8 <- from the log-file
installed version is Java SE Developement Kit 19.0.1
**Modpack Launcher Used**
->curseforge launcher
**Ram Allocated**
-> 12096MB

**Additional context**
->
I changed via command or directly in the config files the amount of claimed chunks (don't know, which of the methods I used to do it)
and also the number of force loaded chunks.
the instance loads but crashes after a few seconds.
I tried to load up an other world where I tested some seeds, the world loads as expected. I checked the serverconfig - files
and the settings for chunk protection and loading is on standard values in that world.
Loading up the same world in modpack version 0.3.8 just works fine.

Crash-logs:
[Crash_After_Update_to_Version_040.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13331386/Crash_After_Update_to_Version_040.txt)
[Crash_After_Update_to_Version_040_2.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13331387/Crash_After_Update_to_Version_040_2.txt)
[Crash_After_Update_to_Version_040_3.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13331524/Crash_After_Update_to_Version_040_3.txt)

**Comment by ChosenArchitect** [comment]
The issue is with the Rechiseled mod so im going to see if I can recreate this issue and maybe a older update will fix this

**Comment by ChosenArchitect** [comment]
Seems it might be fixed with the latest embedium 
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/399d76bf-64eb-444e-9a5c-4d9eb5ccefe2)
Did a lot of testing with the same blocks that caused the crash

**Comment by ChosenArchitect** [comment]
same issue as https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/74

**Comment by Thorton101** [comment]
Hello Cody, 
I first looked on the other issues before opening my bug - report. My crash - log throws other errors than in issue #74 so I opened this one.
Updating to the latest modpack version and my world loads up as intended.
Thank you, Cody for your help and keep up the good work
