### ISSUE TITLE
Crashes When I Open My World Forge 

### ISSUE THREAD

**Issue by SethDredge** [ChosenArchitect/ChosensModdedAdventure#76]
**Describe the bug**
-> game crash when accessing a full world forge while a cobble gen is still feeding world forge 

**To Reproduce**
1. Full world forge (both cobble and world cores)
2. Diamond cobble gen with wood hopper 
3. Right click world forge to access GUI and game crashes 
4. 

**Expected behavior**
-> access to the world forge GUI 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->CMA Chunk by Chunk 0.2.1
**Java Version**
->1.20.1
**Modpack Launcher Used**
->ATLauncher 
**Ram Allocated**
->8 Gigs 

**Additional context**
-> this also happened in the previous mod pack version

**Comment by ChosenArchitect** [comment]
Same as https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/53 waiting on a fix from the mod dev

**Comment by SethDredge** [comment]
Oops sorry chosen I missed that in the known issues thx
