### ISSUE TITLE
Mod suggesstion: Better Inventory Sorter

### ISSUE THREAD

**Issue by lilmayu** [ChosenArchitect/ChosensModdedAdventure#77]
**Is your feature request related to a problem? Please describe.**
-> When sorting, my game lags and sometimes even prints "IllegalStateException" in the chat.

**Describe the solution you'd like**
-> Replace current inventory sorting mod with other: https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Describe alternatives you've considered**
-> https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Mod Sugestions**
-> https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Additional context**
-> pretty please :( it is required on server as well, so clients cannot install it themselves

**Comment by ChosenArchitect** [comment]
I have tried the Inventory Sotryer mod and it doesn't work on a lot of the modded inventories. Will look to see if new options are available.
