### ISSUE TITLE
Mod suggestion: Configured

### ISSUE THREAD

**Issue by lilmayu** [ChosenArchitect/ChosensModdedAdventure#79]
**Is your feature request related to a problem? Please describe.**
-> Unable to configure JEI in Minecraft using ingame button

**Describe the solution you'd like**
-> Add this mod https://www.curseforge.com/minecraft/mc-mods/configured

**Mod Sugestions**
-> https://www.curseforge.com/minecraft/mc-mods/configured

**Additional context**
-> pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by ChosenArchitect** [comment]
Sorry but it is not updated for 1.20.1
![image](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/35053440/7a82fb50-0e0a-4156-99d5-2d9b59f967af)
