### ISSUE TITLE
Modpack Crashes every time

### ISSUE THREAD

**Issue by CDCS369** [ChosenArchitect/ChosensModdedAdventure#8]
Modpack crashes every time I run it, has something to do with create utilities. I have attached a screenshot and the crash report.

[crash-2023-09-29_18.29.03-fml.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12772311/crash-2023-09-29_18.29.03-fml.txt)

![image_2023-09-29_183047505](https://github.com/ChosenArchitect/ChosensModdedAdventure/assets/146491374/43828b90-d466-4f1d-a27c-969c2c1b773d)

**Comment by ChosenArchitect** [comment]
I need to know what modpack version you are on... you didn't follow the template so I am left clueless.

**Comment by CDCS369** [comment]
Sorry, never used github before. I'm using 0.0.3.

**Comment by CDCS369** [comment]
I guess the file was corrupted bc a reinstall fixed it, sorry for wasting your time.

**Comment by ChosenArchitect** [comment]
fixed in 0.1.1
