### ISSUE TITLE
Suggestion: Create Slice & Dice

### ISSUE THREAD

**Issue by tariqk** [ChosenArchitect/ChosensModdedAdventure#80]
### Is your feature request related to a problem? Please describe.

It is not. While adding this mod would be _cool_, if it goes against the vision of the modpack it's okay. There _are_ ways to automate what I intend to do without this mod. It would be _cool_, though, plus I feel like the throughput would be _much_ higher if I used this method.

### Describe the solution you'd like

I'd like to suggest adding [Create Slice & Dice](https://modrinth.com/mod/slice-and-dice "link to Modrinth mod page") into the modpack. It will add ways of automating Farmer's Delight with create, specifically being able to manage large and complex recipes that require processing in a way that involves Create production lines.

### Describe alternatives you've considered

In theory, using the current item and fluid transports, along with modular router setups, could be done, but essentially it's Magic Boxes™ interacting with other Magic Boxes™ in the world. 

Plus, it's _Create_. A giant industrial kitchen? Dedicated to producing meals for players? Sure, I can do it with _other_ mods, but Create always lends itself to giant, very aesthetically-pleasing builds.

### Mod Sugestions

* Obviously [Create Slice & Dice](https://modrinth.com/mod/slice-and-dice "Modrinth link")
* [Nether's Delight](https://www.curseforge.com/minecraft/mc-mods/nethers-delight "Curseforge link") is now updated to Forge 1.20.1.
* As is [Crabber's Delight](https://www.curseforge.com/minecraft/mc-mods/nethers-delight "Curseforge link").
* ~~Also, fr fr, _any_ mod that adds the ability for you to apply knives on potatoes. You telling me that you have a chopping board but there's no way to make sliced potatoes to sautée, or to julienne the slices to make fries? Come _on_, now (this isn't on you, TBH, I've been looking for _months_. You can make weird concoctions with chorus fruit and warped fungi but you can't even sautée potatoes or make fries. Terrible.)~~ Nevermind that, [started a discussion on the main mod](https://github.com/vectorwing/FarmersDelight/discussions/839), that's a better place to bring this up.

### Additional context

Not really applicable.

**Comment by ChosenArchitect** [comment]
Will look into it and see if I can add it without any issue!
