### ISSUE TITLE
My map ticks freeze and my world is gone

### ISSUE THREAD

**Issue by HooZz7** [ChosenArchitect/ChosensModdedAdventure#81]
**Describe the bug**
-> It ocurred 3 times already, my game simply wont update any chunks and any game info, nothing works, entities, chunks, inventory, weapons, stats, nothing

**To Reproduce**
1. play the game
2. quit
3. open map
4. bugged

**Expected behavior**
->ticks froze

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->last
**Java Version**
->last
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->8gb

**Additional context**
-> i cant find this error anywhere on the internet, i've lost 3 worlds already

**Comment by ChosenArchitect** [comment]
I need more info or even the save file
