### ISSUE TITLE
No server pack on recent update

### ISSUE THREAD

**Issue by Papaturts** [ChosenArchitect/ChosensModdedAdventure#82]
**Is your feature request related to a problem? Please describe.**
->  Im not seeing an update server pack for the modpack

**Describe the solution you'd like**
->  Is it possible to get one?

**Describe alternatives you've considered**
->  None atm-great pack

**Mod Sugestions**
->  None atm-great pack

**Additional context**
->

**Comment by lilmayu** [comment]
0.4.2 has server pack: https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure/files/4870336

although, 0.4.1 did not have one, tho.
