### ISSUE TITLE
Moar mod suggestions

### ISSUE THREAD

**Issue by lilmayu** [ChosenArchitect/ChosensModdedAdventure#85]
I'll add more suggestions that I have in this issue. I've already created *three issues suggesting mods* and if I did make an issue for every other suggestion, I guess it would be kinda..messy. Feel free to disagree with any of these mods.

# Suggested mods
## Visual
1. Falling Leaves - https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge
    - Pretty! Also works with modded trees.
2. Skin Layers 3D - https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d
    - Fancier skins

## Performance / Client side
1. Entity Culling - https://www.curseforge.com/minecraft/mc-mods/entityculling
    - Must have mod nowadays. Improved my FPS up to 30% when there are lot of those magma crabs.
2. Fastload - https://www.curseforge.com/minecraft/mc-mods/fastload
    - Well, as the name says. Improves startup times.
4. FastWorkbench, FastFurnace - https://www.curseforge.com/minecraft/mc-mods/fastworkbench, https://www.curseforge.com/minecraft/mc-mods/fastfurnace
    - Improves performance when searching for recipes, moar CPU to the ticking of the world
5. Radium - https://www.curseforge.com/minecraft/mc-mods/radium-reforged
    - Improves generally TPS in terms of mob AI, block ticking, etc.; good stuff!
6. Smooth Chunk Save - https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save
    - Awesome for big worlds, should not conflict with simplebackup
7. Embeddium++ - https://www.curseforge.com/minecraft/mc-mods/embeddium-plus
    - FPS counter, and more. Might turn off True Darkness by default.
8. Rubidium Dynamic Lights - https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged
    - Suprised it is not already included. Must have when exploring! Works with Embeddium++
9. Starlight - https://www.curseforge.com/minecraft/mc-mods/starlight-forge
    - Lighting engine in 1.20 is okayish, but still improves some stuff
10. Oculus Flywheel Compat - https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat
    - Flywheel optimizations when using shaders (flywheel is implemented with create)
11. Smooth boot - https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded
    - Super helpful even when you've got beefy CPU

## Content mods
1. Twilight Forest - https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest
    - This one might be bigger, but I am suprised it isn't in this modpack. Adds super cool dimension, filled with sweet stuff and nostalgia.
2. MrCrayfish's Furniture Mod - https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
    - Moar furniture!

**Comment by ChosenArchitect** [comment]
I added a few of these but I will say some of them are not compatible such as Oculus flywheel because version issues! Thanks for the suggestions!
