### ISSUE TITLE
Bug infinity Diamond

### ISSUE THREAD

**Issue by bhoang15530** [ChosenArchitect/ChosensModdedAdventure#89]
**Describe the bug**
-> I tried using the Life Exchange mod's Balance Stone to change from Gold Ingot to Diamond through Cyclic's Auto Crafting (Crafting Machine). With just 1 Balance Stone and 2 Gold Ingots, they will create an unlimited amount of Diamond.

**To Reproduce**
1. Create the Balance Stone's gold to diamond recipe on the Crafting Machine
2. Transmit power from the Powah (Furnator), and let the Crafting Machine run using the Redstone signal from the Lever.
3. Transfer items from Crafting Machine to Oak Drawer using the PrettyPipes mod
4. As a result, diamonds are generated continuously with only 2 Gold Ingots and 1 Balance Stone

**Expected behavior**
->I thought according to the Recipe, there must be 4 Gold Ingots and 1 Balance Stone to create 1 Diamond, but that's not the case. They keep creating unlimited Diamonds continuously with just 2 gold ingots

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->0.4.3
**Java Version**
->17.0.8
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->10272MB

**Additional context**
->It seems that this bug not only occurs in the Gold Ingot to Diamond recipes but also in the Iron Ingot to Gold Ingot formula (The situation occurs in the Gold Ingot to Diamond formula, 2 Iron Ingot and 1 Balance Stone). It seems several other formulas are also affected.

**Comment by ChosenArchitect** [comment]
Seems to be fixed in the latest Cyclic update and will be fixed in the next update! Thanks for the report!
