### ISSUE TITLE
[0.1.0] Quest "Punch Logs" in Getting Started does only accept Regions Unexplored logs

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/ChosensModdedAdventure#9]
**Describe the bug**
The quest "Punch Logs" in the Getting Started chapter only accepts logs from Regions Unexplored, not every log in the game.
**Expected behavior**
The quest should accept any log.
**Modpack version**
0.1.0

**Comment by ChosenArchitect** [comment]
fixed in 0.1.1
