### ISSUE TITLE
Crashing when using energy conduits

### ISSUE THREAD

**Issue by Papaturts** [ChosenArchitect/ChosensModdedAdventure#90]
**Describe the bug**
Having a crash on a server when using the energy conduits from enderIO
->

**To Reproduce**
1. place/use energy conduits
2. go to nether and come back 
3. crash

**Expected behavior**
-> Server not to crash when being used

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
possible fix-going back to an older version
**Modpack version**
->4.3
**Java Version**
->18.0.2.1, Eclipse Adoptium
**Modpack Launcher Used**
->Server/Kinetic Hosting-Linux (amd64) version 5.15.0-88-generic
**Ram Allocated**
->16gb

**Additional context**
->This is happening on a Hosted/public server for the Modpack
[crash-2023-12-02_07.09.36-server.txt](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13537213/crash-2023-12-02_07.09.36-server.txt)

**Comment by edshPC** [comment]
Same, is it fixed in 5.0?

**Comment by ChosenArchitect** [comment]
This might be a issue until ENDERIO is updated as that mod is still in early beta
