### ISSUE TITLE
Crashes When I Open My Backpack due to MooBloom in a containment jar

### ISSUE THREAD

**Issue by MisterBianco** [ChosenArchitect/ChosensModdedAdventure#92]
# Describe the bug

I have a moobloom in a ars nouveau containment jar inside my backpack. Whenever I open the backpack the game crashes. The server I am playing on is multiplayer and has been updated from a previous version.

---

**To Reproduce**
1.  Put a moobloom in a containment jar
2.  Put jar in backpack
3.  Open backpack
4.  No profit

**Expected behavior**

The backpack to open with no problems.

---

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**

0,5,0

---

**Java Version**

openjdk-17.08

---

**Modpack Launcher Used**

Curseforge

---

**Ram Allocated**

8gb

---

**Additional context**

The error message on crash is: `java.lang.NullPointerException: Cannot invoke "com.faboslav.friendsandfoes.api.MoobloomVariant.getName()" because the return value of "com.faboslav.friendsandfoes.api.MoobloomVariantManager.getDefaultMoobloomVariant()" is null`

I have attached the [crash report](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/13698131/crash-2023-12-17_15.46.33-client.txt)

---

PS:

I went to the friends and foe mod github page and found they have a new mod version 2.0.5 for mc-1.20.1 and installed that in everyones mod folder and the crash no longer happens.

Thus the fix is to simply bump the friends & foes mod version from 2.0.4 to 2.0.5.

Previously I tried disabling mooblooms in the f&f config file figuring perhaps it was due to a moobloom wandering into render distance but alas it was not. 🤣

**Comment by ChosenArchitect** [comment]
Just dont some testing on the latest patch and I cant seem to get this to recreate so I hope that this means one of the mods somehow fixed this in one of the updates as I tried everything to get it to crash and nothing! I hope this next update fixes this issue for you :D

**Comment by MisterBianco** [comment]
I mean my P.S. explained how to fix the issue and your note in discord said friends and foes was updated so unless you lied in the update note then it should be fixed! 🥳 🎆 

Merry Christmas and happy new years.
