### ISSUE TITLE
Create C&A's capacitors are uncraftable due to recipe conflict with Create Deco

### ISSUE THREAD

**Issue by Ramelstag** [ChosenArchitect/ChosensModdedAdventure#93]
You need zinc sheets for the capacitor item, and, when placing zinc ingots on the mechanical press, you get Create Deco's zinc sheets, which is not on the dictionary and thus can't be used for Create C&A's recipes.

1. Give the mechanical press a zinc ingot
2. Bonk
3. Create Deco zinc plate that can't be used to crafting the capacitor item.

Modpack version: 0.5

Expected behavior
This is more of a Create A&C and Create Deco issue for not having a dictionary entry so both could be used for the same things, but maybe something could be done with crafttweaks, or another method to fix that on the modpack's side.

**Comment by ChosenArchitect** [comment]
Working on fixing this now and will be fixed in next update!
