### ISSUE TITLE
Exit Code 1 on launch

### ISSUE THREAD

**Issue by ThatTLeef** [ChosenArchitect/ChosensModdedAdventure#99]
As the title says, the modpack crashes on launch and gives me an Exit Code 1.

Pack version is 6.1, but also crashes on 6.0. I was trying to update from version 3 something, I think. Everything seems up to date. Launching out of Overwolf.

**Comment by frogtosser** [comment]
https://www.reddit.com/r/Minecraft/comments/18qgjnr/pls_help_chosens_modded_adventure_keeps_crashing/
